from PyQt5 import QtWidgets, QtCore, QtGui
from view.components import result_table, annotation_table, bar_graph

class History_Accordion:
    def __init__(self):
        self.history_accordion = QtWidgets.QWidget()
        self.history_accordion.setGeometry(QtCore.QRect(0, 0, 141, 113))
        self.history_accordion.setObjectName("history_accordion")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.history_accordion)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.history_table = QtWidgets.QTableWidget(self.history_accordion)
        self.history_table.setStyleSheet("")
        self.history_table.setAutoScrollMargin(16)
        self.history_table.setDragEnabled(True)
        self.history_table.setAlternatingRowColors(True)
        self.history_table.setTextElideMode(QtCore.Qt.ElideNone)
        self.history_table.setObjectName("history_table")
        self.history_table.setColumnCount(6)
        self.history_table.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        item.setFont(font)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.history_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.history_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.history_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.history_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.history_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.history_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setItem(5, 5, item)
        self.history_table.horizontalHeader().setCascadingSectionResizes(True)
        self.history_table.horizontalHeader().setDefaultSectionSize(170)
        self.history_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_9.addWidget(self.history_table)
        self.pushButton_13 = QtWidgets.QPushButton(self.history_accordion)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_9.addWidget(self.pushButton_13, 0, QtCore.Qt.AlignLeft)

        """retranslateUi"""
        _translate = QtCore.QCoreApplication.translate
        self.history_table.setSortingEnabled(True)
        item = self.history_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Select"))
        item = self.history_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Timestamp"))
        item = self.history_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expression Type"))
        item = self.history_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.history_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "MAC Address"))
        item = self.history_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Expression"))
        __sortingEnabled = self.history_table.isSortingEnabled()
        self.history_table.setSortingEnabled(False)
        item = self.history_table.item(0, 1)
        item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
        item = self.history_table.item(0, 2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.history_table.item(0, 3)
        item.setText(_translate("MainWindow", "125.42.0.1"))
        item = self.history_table.item(0, 4)
        item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
        item = self.history_table.item(0, 5)
        item.setText(_translate("MainWindow", "Sample Expression"))
        item = self.history_table.item(1, 1)
        item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
        item = self.history_table.item(1, 2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.history_table.item(1, 3)
        item.setText(_translate("MainWindow", "125.42.0.1"))
        item = self.history_table.item(1, 4)
        item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
        item = self.history_table.item(1, 5)
        item.setText(_translate("MainWindow", "Sample Expression"))
        item = self.history_table.item(2, 1)
        item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
        item = self.history_table.item(2, 2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.history_table.item(2, 3)
        item.setText(_translate("MainWindow", "125.42.0.1"))
        item = self.history_table.item(2, 4)
        item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
        item = self.history_table.item(2, 5)
        item.setText(_translate("MainWindow", "Sample Expression"))
        item = self.history_table.item(3, 1)
        item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
        item = self.history_table.item(3, 2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.history_table.item(3, 3)
        item.setText(_translate("MainWindow", "125.42.0.1"))
        item = self.history_table.item(3, 4)
        item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
        item = self.history_table.item(3, 5)
        item.setText(_translate("MainWindow", "Sample Expression"))
        item = self.history_table.item(4, 1)
        item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
        item = self.history_table.item(4, 2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.history_table.item(4, 3)
        item.setText(_translate("MainWindow", "125.42.0.1"))
        item = self.history_table.item(4, 4)
        item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
        item = self.history_table.item(4, 5)
        item.setText(_translate("MainWindow", "Sample Expression"))
        item = self.history_table.item(5, 1)
        item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
        item = self.history_table.item(5, 2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.history_table.item(5, 3)
        item.setText(_translate("MainWindow", "125.42.0.1"))
        item = self.history_table.item(5, 4)
        item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
        item = self.history_table.item(5, 5)
        item.setText(_translate("MainWindow", "Sample Expression"))
        self.history_table.setSortingEnabled(__sortingEnabled)
        self.pushButton_13.setText(_translate("MainWindow", "Apply Expression"))

    def get_accordion(self):
        return self.history_accordion
