from PyQt5 import QtWidgets, QtCore, QtGui
from view.components import result_table, annotation_table, bar_graph
from view.home_tab.detailed_view import DetailedView

class Home:
	def __init__(self):
		self.tab_1 = QtWidgets.QWidget()
		self.tab_1.setObjectName("tab_1")
		self.gridLayout_tab_1 = QtWidgets.QGridLayout(self.tab_1)
		self.gridLayout_tab_1.setObjectName("gridLayout_tab_1")
		self.scrollArea = QtWidgets.QScrollArea(self.tab_1)
		self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.scrollArea.setWidgetResizable(True)
		self.scrollArea.setObjectName("scrollArea")
		self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
		self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1222, 1452))
		self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.home_top_view = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
		self.home_top_view.setObjectName("home_top_view")
		self.gridLayout_70 = QtWidgets.QGridLayout(self.home_top_view)
		self.gridLayout_70.setObjectName("gridLayout_70")
		self.search_bar = QtWidgets.QFrame(self.home_top_view)
		self.search_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.search_bar.setFrameShadow(QtWidgets.QFrame.Plain)
		self.search_bar.setObjectName("search_bar")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.search_bar)
		self.verticalLayout.setContentsMargins(9, 9, -1, -1)
		self.verticalLayout.setSpacing(4)
		self.verticalLayout.setObjectName("verticalLayout")
		self.label_10 = QtWidgets.QLabel(self.search_bar)
		self.label_10.setStyleSheet("")
		self.label_10.setObjectName("label_10")
		self.verticalLayout.addWidget(self.label_10)
		self.search_expression_bar = QtWidgets.QLineEdit(self.search_bar)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.search_expression_bar.sizePolicy().hasHeightForWidth())
		self.search_expression_bar.setSizePolicy(sizePolicy)
		self.search_expression_bar.setMinimumSize(QtCore.QSize(200, 30))
		self.search_expression_bar.setMaximumSize(QtCore.QSize(300, 30))
		self.search_expression_bar.setText("")
		self.search_expression_bar.setObjectName("search_expression_bar")
		self.verticalLayout.addWidget(self.search_expression_bar)
		self.tagSearch_2 = QtWidgets.QFrame(self.search_bar)
		self.tagSearch_2.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.tagSearch_2.setFrameShadow(QtWidgets.QFrame.Raised)
		self.tagSearch_2.setObjectName("tagSearch_2")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.tagSearch_2)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setSpacing(0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.tagSearch = QtWidgets.QFrame(self.tagSearch_2)
		self.tagSearch.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.tagSearch.setFrameShadow(QtWidgets.QFrame.Plain)
		self.tagSearch.setObjectName("tagSearch")
		self.gridLayout_18 = QtWidgets.QGridLayout(self.tagSearch)
		self.gridLayout_18.setObjectName("gridLayout_18")
		self.label_8 = QtWidgets.QLabel(self.tagSearch)
		self.label_8.setObjectName("label_8")
		self.gridLayout_18.addWidget(self.label_8, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
		self.search_tag = QtWidgets.QComboBox(self.tagSearch)
		self.search_tag.setMinimumSize(QtCore.QSize(80, 0))
		self.search_tag.setMaximumSize(QtCore.QSize(150, 27))
		self.search_tag.setPlaceholderText("")
		self.search_tag.setObjectName("search_tag")
		self.search_tag.addItem("")
		self.search_tag.addItem("")
		self.gridLayout_18.addWidget(self.search_tag, 0, 2, 1, 1)
		spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout_18.addItem(spacerItem, 0, 1, 1, 1)
		self.horizontalLayout.addWidget(self.tagSearch, 0, QtCore.Qt.AlignLeft)
		self.search_button = QtWidgets.QPushButton(self.tagSearch_2)
		self.search_button.setMaximumSize(QtCore.QSize(150, 16777215))
		self.search_button.setObjectName("search_button")
		self.horizontalLayout.addWidget(self.search_button)
		self.verticalLayout.addWidget(self.tagSearch_2, 0, QtCore.Qt.AlignLeft)
		self.gridLayout_70.addWidget(self.search_bar, 0, 0, 1, 2)
		self.frame_21 = QtWidgets.QFrame(self.home_top_view)
		self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_21.setObjectName("frame_21")
		self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_21)
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.universalRecord = QtWidgets.QPushButton(self.frame_21)
		self.universalRecord.setCheckable(True)
		self.universalRecord.setChecked(True)
		self.universalRecord.setObjectName("universalRecord")
		self.gridLayout_3.addWidget(self.universalRecord, 0, 0, 1, 1)
		self.gridLayout_70.addWidget(self.frame_21, 0, 2, 1, 1, QtCore.Qt.AlignRight | QtCore.Qt.AlignBottom)


		""" FILTER START """

		self.search_filters = QtWidgets.QFrame(self.home_top_view)
		self.search_filters.setMinimumSize(QtCore.QSize(250, 0))
		self.search_filters.setMaximumSize(QtCore.QSize(250, 16777215))
		self.search_filters.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.search_filters.setObjectName("search_filters")

		self.gridLayout_2 = QtWidgets.QGridLayout(self.search_filters)
		self.gridLayout_2.setVerticalSpacing(7)
		self.gridLayout_2.setObjectName("gridLayout_2")

		self.label_filters = QtWidgets.QLabel(self.search_filters)
		self.label_filters.setMaximumSize(QtCore.QSize(16777215, 80))
		self.label_filters.setStyleSheet("")
		self.label_filters.setObjectName("label_filters")

		self.label_value_filter = QtWidgets.QLabel(self.search_filters)
		self.label_value_filter.setMaximumSize(QtCore.QSize(16777215, 12))
		self.label_value_filter.setObjectName("label_value_filter")
		self.gridLayout_2.addWidget(self.label_value_filter, 0, 1, 1, 1)

		self.label_user_profile = QtWidgets.QLabel(self.search_filters)
		self.label_user_profile.setMaximumSize(QtCore.QSize(16777215, 12))
		self.label_user_profile.setObjectName("label_user_profile")
		self.gridLayout_2.addWidget(self.label_user_profile, 1, 0, 1, 1)

		self.label_ip_address = QtWidgets.QLabel(self.search_filters)
		self.label_ip_address.setMaximumSize(QtCore.QSize(100, 16777215))
		self.label_ip_address.setObjectName("label_ip_address")
		self.gridLayout_2.addWidget(self.label_ip_address, 2, 0, 1, 1)
		self.ip_dropdown = QtWidgets.QComboBox(self.search_filters)
		self.ip_dropdown.setMaximumSize(QtCore.QSize(150, 20))
		self.ip_dropdown.setObjectName("ip_dropdown")
		self.ip_dropdown.addItem("goodbye")
		self.ip_dropdown.addItem("")
		self.ip_dropdown.addItem("")
		self.gridLayout_2.addWidget(self.ip_dropdown, 2, 1, 1, 1)

		self.label_mac_address = QtWidgets.QLabel(self.search_filters)
		self.label_mac_address.setMaximumSize(QtCore.QSize(100, 16777215))
		self.label_mac_address.setObjectName("label_mac_address")
		self.gridLayout_2.addWidget(self.label_mac_address, 3, 0, 1, 1)
		self.mac_dropdown = QtWidgets.QComboBox(self.search_filters)
		self.mac_dropdown.setMaximumSize(QtCore.QSize(150, 20))
		self.mac_dropdown.setObjectName("mac_dropdown")
		self.mac_dropdown.addItem("hello")
		self.mac_dropdown.addItem("")
		self.mac_dropdown.addItem("")
		self.gridLayout_2.addWidget(self.mac_dropdown, 3, 1, 1, 1)

		self.label_type = QtWidgets.QLabel(self.search_filters)
		self.label_type.setMaximumSize(QtCore.QSize(16777215, 15))
		self.label_type.setObjectName("label_type")
		self.gridLayout_2.addWidget(self.label_type, 4, 0, 1, 1)

		self.label_value_type = QtWidgets.QLabel(self.search_filters)
		self.label_value_type.setObjectName("label_2")
		self.gridLayout_2.addWidget(self.label_value_type, 4, 1, 1, 1)


		""" CHECKBOXES    """

		self.checkBox_all_artifacts = QtWidgets.QCheckBox(self.search_filters)
		self.checkBox_all_artifacts.setText("")
		self.checkBox_all_artifacts.setObjectName("checkBox_all_artifacts")
		self.gridLayout_2.addWidget(self.checkBox_all_artifacts, 5, 1, 1, 1)
		self.label_all_artifacts = QtWidgets.QLabel(self.search_filters)
		font = QtGui.QFont()
		self.label_all_artifacts.setFont(font)
		self.label_all_artifacts.setObjectName("label_all_artifacts")
		self.gridLayout_2.addWidget(self.label_all_artifacts, 5, 0, 1, 1)

		self.checkBox_screenshot = QtWidgets.QCheckBox(self.search_filters)
		self.checkBox_screenshot.setText("")
		self.checkBox_screenshot.setObjectName("checkBox_screenshot")
		self.gridLayout_2.addWidget(self.checkBox_screenshot, 6, 1, 1, 1)
		self.label_screenshot = QtWidgets.QLabel(self.search_filters)
		self.label_screenshot.setObjectName("label_screenshot")
		self.gridLayout_2.addWidget(self.label_screenshot, 6, 0, 1, 1)

		self.checkBox_video = QtWidgets.QCheckBox(self.search_filters)
		self.checkBox_video.setText("")
		self.checkBox_video.setObjectName("checkBox_video")
		self.gridLayout_2.addWidget(self.checkBox_video, 7, 1, 1, 1)
		self.label_video = QtWidgets.QLabel(self.search_filters)
		self.label_video.setObjectName("label_video")
		self.gridLayout_2.addWidget(self.label_video, 7, 0, 1, 1)

		self.checkBox_network = QtWidgets.QCheckBox(self.search_filters)
		self.checkBox_network.setText("")
		self.checkBox_network.setObjectName("checkBox_network")
		self.gridLayout_2.addWidget(self.checkBox_network, 8, 1, 1, 1)
		self.label_network = QtWidgets.QLabel(self.search_filters)
		self.label_network.setObjectName("label_network")
		self.gridLayout_2.addWidget(self.label_network, 8, 0, 1, 1)

		self.checkBox_process = QtWidgets.QCheckBox(self.search_filters)
		self.checkBox_process.setText("")
		self.checkBox_process.setObjectName("checkBox_process")
		self.gridLayout_2.addWidget(self.checkBox_process, 9, 1, 1, 1)
		self.label_process = QtWidgets.QLabel(self.search_filters)
		self.label_process.setObjectName("label_process")
		self.gridLayout_2.addWidget(self.label_process, 9, 0, 1, 1)

		self.checkBox_keystroke = QtWidgets.QCheckBox(self.search_filters)
		self.checkBox_keystroke.setText("")
		self.checkBox_keystroke.setObjectName("checkBox_keystroke")
		self.gridLayout_2.addWidget(self.checkBox_keystroke, 10, 1, 1, 1)
		self.label_keystroke = QtWidgets.QLabel(self.search_filters)
		self.label_keystroke.setObjectName("label_keystroke")
		self.gridLayout_2.addWidget(self.label_keystroke, 10, 0, 1, 1)

		self.checkBox_mouse_action = QtWidgets.QCheckBox(self.search_filters)
		self.checkBox_mouse_action.setText("")
		self.checkBox_mouse_action.setObjectName("checkBox_mouse_action")
		self.gridLayout_2.addWidget(self.checkBox_mouse_action, 11, 1, 1, 1)
		self.label_mouse_action = QtWidgets.QLabel(self.search_filters)
		self.label_mouse_action.setObjectName("label_mouse_action")
		self.gridLayout_2.addWidget(self.label_mouse_action, 11, 0, 1, 1)

		self.checkBox_windowHistory = QtWidgets.QCheckBox(self.search_filters)
		self.checkBox_windowHistory.setText("")
		self.checkBox_windowHistory.setObjectName("checkBox_windowHistory")
		self.gridLayout_2.addWidget(self.checkBox_windowHistory, 12, 1, 1, 1)
		self.label_window_history = QtWidgets.QLabel(self.search_filters)
		self.label_window_history.setObjectName("label_window_history")
		self.gridLayout_2.addWidget(self.label_window_history, 12, 0, 1, 1)

		self.checkBox_system_call = QtWidgets.QCheckBox(self.search_filters)
		self.checkBox_system_call.setText("")
		self.checkBox_system_call.setObjectName("checkBox_system_call")
		self.gridLayout_2.addWidget(self.checkBox_system_call, 13, 1, 1, 1)
		self.label_system_call = QtWidgets.QLabel(self.search_filters)
		self.label_system_call.setObjectName("label_system_call")
		self.gridLayout_2.addWidget(self.label_system_call, 13, 0, 1, 1)

		self.checkBox_history = QtWidgets.QCheckBox(self.search_filters)
		self.checkBox_history.setText("")
		self.checkBox_history.setObjectName("checkBox_history")
		self.gridLayout_2.addWidget(self.checkBox_history, 14, 1, 1, 1)
		self.label_history = QtWidgets.QLabel(self.search_filters)
		self.label_history.setObjectName("label_history")
		self.gridLayout_2.addWidget(self.label_history, 14, 0, 1, 1)

		self.checkBox_log = QtWidgets.QCheckBox(self.search_filters)
		self.checkBox_log.setText("")
		self.checkBox_log.setObjectName("checkBox_log")
		self.gridLayout_2.addWidget(self.checkBox_log, 15, 1, 1, 1)
		self.label_log = QtWidgets.QLabel(self.search_filters)
		self.label_log.setObjectName("label_log")
		self.gridLayout_2.addWidget(self.label_log, 15, 0, 1, 1)

		""" CHECKBOXES END """

		self.label_date_time = QtWidgets.QLabel(self.search_filters)
		self.label_date_time.setMaximumSize(QtCore.QSize(16777215, 80))
		self.label_date_time.setStyleSheet("")
		self.label_date_time.setObjectName("label_date_time")
		self.gridLayout_2.addWidget(self.label_date_time, 16, 0, 1, 1)
		self.gridLayout_2.addWidget(self.label_filters, 0, 0, 1, 1)
		self.label_value_date_time = QtWidgets.QLabel(self.search_filters)
		self.label_value_date_time.setStyleSheet("")
		self.label_value_date_time.setObjectName("label_value_date_time")
		self.gridLayout_2.addWidget(self.label_value_date_time, 16, 1, 1, 1)

		self.label_start_date = QtWidgets.QLabel(self.search_filters)
		self.label_start_date.setObjectName("label_start_date")
		self.gridLayout_2.addWidget(self.label_start_date, 17, 0, 1, 1)
		self.start_date_widget = QtWidgets.QDateEdit(self.search_filters)
		self.start_date_widget.setObjectName("dateEdit")
		self.gridLayout_2.addWidget(self.start_date_widget, 17, 1, 1, 1)

		self.label_start_time = QtWidgets.QLabel(self.search_filters)
		self.label_start_time.setObjectName("label_start_time")
		self.gridLayout_2.addWidget(self.label_start_time, 18, 0, 1, 1)
		self.start_time_widget = QtWidgets.QTimeEdit(self.search_filters)
		self.start_time_widget.setObjectName("timeEdit")
		self.gridLayout_2.addWidget(self.start_time_widget, 18, 1, 1, 1)

		self.label_end_date = QtWidgets.QLabel(self.search_filters)
		self.label_end_date.setObjectName("label_end_date")
		self.gridLayout_2.addWidget(self.label_end_date, 19, 0, 1, 1)
		self.end_date_widget = QtWidgets.QDateEdit(self.search_filters)
		self.end_date_widget.setObjectName("end_date_widget")
		self.gridLayout_2.addWidget(self.end_date_widget, 19, 1, 1, 1)

		self.end_time_widget = QtWidgets.QTimeEdit(self.search_filters)
		self.end_time_widget.setObjectName("end_time_widget")
		self.gridLayout_2.addWidget(self.end_time_widget, 20, 1, 1, 1)
		self.label_end_time = QtWidgets.QLabel(self.search_filters)
		self.label_end_time.setObjectName("label_end_time")
		self.gridLayout_2.addWidget(self.label_end_time, 20, 0, 1, 1)

		self.gridLayout_70.addWidget(self.search_filters, 1, 0, 1, 1)

		""" FILTERS END """

		self.avert_table = QtWidgets.QFrame(self.home_top_view)
		self.avert_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.avert_table.setFrameShadow(QtWidgets.QFrame.Plain)
		self.avert_table.setObjectName("avert_table")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.avert_table)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.label_9 = QtWidgets.QLabel(self.avert_table)
		font = QtGui.QFont()
		self.label_9.setFont(font)
		self.label_9.setObjectName("label_9")
		self.verticalLayout_3.addWidget(self.label_9)

		# global table_result
		# table_result = QtWidgets.QTableWidget(self.avert_table)
		# table_result = result_table.ResultTable(table_result)

		global table_result
		table_result = result_table.ResultTable()
		table_result.startTable(QtWidgets.QTableWidget(self.avert_table))
		self.table_result = table_result

		self.verticalLayout_3.addWidget(table_result.getTable())
		self.frame_14 = QtWidgets.QFrame(self.avert_table)
		self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.frame_14.setFrameShadow(QtWidgets.QFrame.Plain)
		self.frame_14.setObjectName("frame_14")
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_14)
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.exportButton = QtWidgets.QPushButton(self.frame_14)
		self.exportButton.setObjectName("exportButton")
		self.horizontalLayout_5.addWidget(self.exportButton)

		self.pushButton_15 = QtWidgets.QPushButton(self.frame_14)
		self.pushButton_15.setObjectName("pushButton_15")
		self.horizontalLayout_5.addWidget(self.pushButton_15)

		self.pushButton_16 = QtWidgets.QPushButton(self.frame_14)
		self.pushButton_16.setObjectName("pushButton_16")
		self.horizontalLayout_5.addWidget(self.pushButton_16)
		self.verticalLayout_3.addWidget(self.frame_14, 0, QtCore.Qt.AlignLeft)
		self.gridLayout_70.addWidget(self.avert_table, 1, 1, 1, 2)
		self.verticalLayout_4.addWidget(self.home_top_view)

		""" Accordions Start"""

		self.toolBox_accordion = QtWidgets.QToolBox(self.scrollAreaWidgetContents_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.toolBox_accordion.sizePolicy().hasHeightForWidth())
		self.toolBox_accordion.setSizePolicy(sizePolicy)
		self.toolBox_accordion.setMinimumSize(QtCore.QSize(0, 700))
		self.toolBox_accordion.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.toolBox_accordion.setObjectName("toolBox_accordion")


		""" DetailedViewAccordion Start """
		self.detailed_view_accordion = DetailedView()
		self.toolBox_accordion.addItem(self.detailed_view_accordion.get_accordion(), "DetailedView")
		""" DetailedViewAccordion End """

		self.visualization_accordion_20 = QtWidgets.QWidget()
		self.visualization_accordion_20.setGeometry(QtCore.QRect(0, 0, 429, 443))
		self.visualization_accordion_20.setObjectName("visualization_accordion_20")
		self.gridLayout_9 = QtWidgets.QGridLayout(self.visualization_accordion_20)
		self.gridLayout_9.setObjectName("gridLayout_9")
		self.visualization_tabs = QtWidgets.QTabWidget(self.visualization_accordion_20)
		self.visualization_tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.visualization_tabs.setObjectName("visualization_tabs")
		self.type = QtWidgets.QWidget()
		self.type.setObjectName("type")
		self.gridLayout = QtWidgets.QGridLayout(self.type)
		self.gridLayout.setObjectName("gridLayout")
		self.visualization_selection = QtWidgets.QFrame(self.type)
		self.visualization_selection.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.visualization_selection.setFrameShadow(QtWidgets.QFrame.Plain)
		self.visualization_selection.setObjectName("visualization_selection")
		self.gridLayout_13 = QtWidgets.QGridLayout(self.visualization_selection)
		self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_13.setObjectName("gridLayout_13")
		self.radioButton_2 = QtWidgets.QRadioButton(self.visualization_selection)
		self.radioButton_2.setObjectName("radioButton_2")
		self.gridLayout_13.addWidget(self.radioButton_2, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
		self.radioButton_4 = QtWidgets.QRadioButton(self.visualization_selection)
		self.radioButton_4.setObjectName("radioButton_4")
		self.gridLayout_13.addWidget(self.radioButton_4, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
		self.radioButton = QtWidgets.QRadioButton(self.visualization_selection)
		self.radioButton.setChecked(True)
		self.radioButton.setObjectName("radioButton")
		self.gridLayout_13.addWidget(self.radioButton, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
		self.gridLayout.addWidget(self.visualization_selection, 0, 0, 1, 1)
		self.visualization_generators = QtWidgets.QFrame(self.type)
		self.visualization_generators.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.visualization_generators.setFrameShadow(QtWidgets.QFrame.Plain)
		self.visualization_generators.setObjectName("visualization_generators")
		self.gridLayout_12 = QtWidgets.QGridLayout(self.visualization_generators)
		self.gridLayout_12.setObjectName("gridLayout_12")
		spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout_12.addItem(spacerItem1, 0, 0, 1, 1)
		spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.gridLayout_12.addItem(spacerItem2, 0, 1, 1, 1)
		self.pushButton_5 = QtWidgets.QPushButton(self.visualization_generators)
		self.pushButton_5.setObjectName("pushButton_5")
		self.gridLayout_12.addWidget(self.pushButton_5, 1, 0, 1, 1)
		self.pushButton_6 = QtWidgets.QPushButton(self.visualization_generators)
		self.pushButton_6.setObjectName("pushButton_6")
		self.gridLayout_12.addWidget(self.pushButton_6, 1, 1, 1, 1)
		self.gridLayout.addWidget(self.visualization_generators, 1, 3, 1, 1)
		spacerItem3 = QtWidgets.QSpacerItem(399, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
		spacerItem4 = QtWidgets.QSpacerItem(466, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
		self.visualization_tabs.addTab(self.type, "")
		self.pie_chart = QtWidgets.QWidget()
		self.pie_chart.setObjectName("pie_chart")
		self.gridLayout_10 = QtWidgets.QGridLayout(self.pie_chart)
		self.gridLayout_10.setObjectName("gridLayout_10")
		self.widget = QtWidgets.QWidget(self.pie_chart)
		self.widget.setObjectName("widget")
		self.gridLayout_34 = QtWidgets.QGridLayout(self.widget)
		self.gridLayout_34.setObjectName("gridLayout_34")
		self.timeline_metadata_2 = QtWidgets.QFrame(self.widget)
		self.timeline_metadata_2.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.timeline_metadata_2.setFrameShadow(QtWidgets.QFrame.Plain)
		self.timeline_metadata_2.setObjectName("timeline_metadata_2")
		self.gridLayout_16 = QtWidgets.QGridLayout(self.timeline_metadata_2)
		self.gridLayout_16.setObjectName("gridLayout_16")
		self.label_91 = QtWidgets.QLabel(self.timeline_metadata_2)
		self.label_91.setObjectName("label_91")
		self.gridLayout_16.addWidget(self.label_91, 1, 0, 1, 1)
		self.lineEdit_4 = QtWidgets.QLineEdit(self.timeline_metadata_2)
		self.lineEdit_4.setText("")
		self.lineEdit_4.setObjectName("lineEdit_4")
		self.gridLayout_16.addWidget(self.lineEdit_4, 1, 1, 1, 1)
		self.label_90 = QtWidgets.QLabel(self.timeline_metadata_2)
		self.label_90.setObjectName("label_90")
		self.gridLayout_16.addWidget(self.label_90, 0, 0, 1, 1)
		self.gridLayout_34.addWidget(self.timeline_metadata_2, 0, 0, 1, 1, QtCore.Qt.AlignTop)
		self.timeline_title_2 = QtWidgets.QFrame(self.widget)
		self.timeline_title_2.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.timeline_title_2.setFrameShadow(QtWidgets.QFrame.Raised)
		self.timeline_title_2.setObjectName("timeline_title_2")
		self.gridLayout_17 = QtWidgets.QGridLayout(self.timeline_title_2)
		self.gridLayout_17.setObjectName("gridLayout_17")
		self.label_92 = QtWidgets.QLabel(self.timeline_title_2)
		self.label_92.setObjectName("label_92")
		self.gridLayout_17.addWidget(self.label_92, 0, 0, 1, 1)
		self.label_93 = QtWidgets.QLabel(self.timeline_title_2)
		self.label_93.setObjectName("label_93")
		self.gridLayout_17.addWidget(self.label_93, 1, 0, 1, 1)
		self.lineEdit_5 = QtWidgets.QLineEdit(self.timeline_title_2)
		self.lineEdit_5.setObjectName("lineEdit_5")
		self.gridLayout_17.addWidget(self.lineEdit_5, 1, 1, 1, 1)
		self.frame_4 = QtWidgets.QFrame(self.timeline_title_2)
		self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_4.setObjectName("frame_4")
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.gridLayout_17.addWidget(self.frame_4, 2, 1, 1, 1)
		self.gridLayout_34.addWidget(self.timeline_title_2, 0, 1, 1, 1, QtCore.Qt.AlignTop)
		self.frame_12 = QtWidgets.QFrame(self.widget)
		self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
		self.frame_12.setObjectName("frame_12")
		self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_12)
		self.gridLayout_15.setObjectName("gridLayout_15")
		self.label_94 = QtWidgets.QLabel(self.frame_12)
		self.label_94.setMaximumSize(QtCore.QSize(301, 241))
		self.label_94.setText("")
		self.label_94.setPixmap(QtGui.QPixmap("view/assets/pie-chart-too-few-slices.png"))
		self.label_94.setObjectName("label_94")
		self.gridLayout_15.addWidget(self.label_94, 0, 0, 1, 1)
		self.gridLayout_34.addWidget(self.frame_12, 1, 0, 1, 2)
		self.gridLayout_10.addWidget(self.widget, 0, 0, 1, 1)
		self.visualization_tabs.addTab(self.pie_chart, "")
		self.bar_graph = QtWidgets.QWidget()
		self.bar_graph.setObjectName("bar_graph")
		self.gridLayout_37 = QtWidgets.QGridLayout(self.bar_graph)
		self.gridLayout_37.setObjectName("gridLayout_37")
		self.Bar_Graph_Area_123 = QtWidgets.QScrollArea(self.bar_graph)
		self.Bar_Graph_Area_123.setWidgetResizable(True)
		self.Bar_Graph_Area_123.setObjectName("Bar_Graph_Area_123")
		self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
		self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 72, 16))
		self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
		self.Bar_Graph_Area_123.setWidget(self.scrollAreaWidgetContents_2)
		# bar graph addition
		self.Bar_Graph_Area_123.setWidget(bar_graph.add_bar_graph())
		self.gridLayout_37.addWidget(self.Bar_Graph_Area_123, 0, 0, 1, 1)
		self.visualization_tabs.addTab(self.bar_graph, "")
		self.timeline = QtWidgets.QWidget()
		self.timeline.setObjectName("timeline")
		self.gridLayout_11 = QtWidgets.QGridLayout(self.timeline)
		self.gridLayout_11.setObjectName("gridLayout_11")
		self.scrollArea_2 = QtWidgets.QScrollArea(self.timeline)
		self.scrollArea_2.setFocusPolicy(QtCore.Qt.StrongFocus)
		self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
		self.scrollArea_2.setLineWidth(1)
		self.scrollArea_2.setWidgetResizable(True)
		self.scrollArea_2.setObjectName("scrollArea_2")
		self.scrollAreaWidgetContents = QtWidgets.QWidget()
		self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 572, 265))
		self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
		self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
		self.gridLayout_6.setObjectName("gridLayout_6")
		self.timeline_footer = QtWidgets.QFrame(self.scrollAreaWidgetContents)
		self.timeline_footer.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.timeline_footer.setFrameShadow(QtWidgets.QFrame.Plain)
		self.timeline_footer.setObjectName("timeline_footer")
		self.gridLayout_8 = QtWidgets.QGridLayout(self.timeline_footer)
		self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_8.setObjectName("gridLayout_8")
		self.timeline_legend = QtWidgets.QFrame(self.timeline_footer)
		self.timeline_legend.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.timeline_legend.setFrameShadow(QtWidgets.QFrame.Raised)
		self.timeline_legend.setObjectName("timeline_legend")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.timeline_legend)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.label_35 = QtWidgets.QLabel(self.timeline_legend)
		self.label_35.setObjectName("label_35")
		self.verticalLayout_2.addWidget(self.label_35)
		self.listWidget = QtWidgets.QListWidget(self.timeline_legend)
		self.listWidget.setObjectName("listWidget")
		item = QtWidgets.QListWidgetItem()
		self.listWidget.addItem(item)
		item = QtWidgets.QListWidgetItem()
		self.listWidget.addItem(item)
		item = QtWidgets.QListWidgetItem()
		self.listWidget.addItem(item)
		item = QtWidgets.QListWidgetItem()
		self.listWidget.addItem(item)
		item = QtWidgets.QListWidgetItem()
		self.listWidget.addItem(item)
		item = QtWidgets.QListWidgetItem()
		self.listWidget.addItem(item)
		item = QtWidgets.QListWidgetItem()
		self.listWidget.addItem(item)
		item = QtWidgets.QListWidgetItem()
		self.listWidget.addItem(item)
		self.verticalLayout_2.addWidget(self.listWidget)
		self.gridLayout_8.addWidget(self.timeline_legend, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
		self.frame_3 = QtWidgets.QFrame(self.timeline_footer)
		self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
		self.frame_3.setObjectName("frame_3")
		self.line = QtWidgets.QFrame(self.frame_3)
		self.line.setGeometry(QtCore.QRect(10, 50, 341, 20))
		self.line.setFrameShape(QtWidgets.QFrame.HLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.line_2 = QtWidgets.QFrame(self.frame_3)
		self.line_2.setGeometry(QtCore.QRect(20, 60, 3, 61))
		self.line_2.setStyleSheet("background-color: rgb(170, 0, 0);\n"
															"border-color: rgb(170, 0, 0);")
		self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.line_3 = QtWidgets.QFrame(self.frame_3)
		self.line_3.setGeometry(QtCore.QRect(70, 0, 3, 61))
		self.line_3.setStyleSheet("background-color: rgb(170, 0, 0);\n"
															"border-color: rgb(170, 0, 0);")
		self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_3.setObjectName("line_3")
		self.line_5 = QtWidgets.QFrame(self.frame_3)
		self.line_5.setGeometry(QtCore.QRect(230, 0, 3, 61))
		self.line_5.setStyleSheet("background-color: rgb(170, 0, 0);\n"
															"border-color: rgb(170, 0, 0);")
		self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_5.setObjectName("line_5")
		self.line_6 = QtWidgets.QFrame(self.frame_3)
		self.line_6.setGeometry(QtCore.QRect(280, 60, 3, 61))
		self.line_6.setStyleSheet("background-color: rgb(170, 0, 0);\n"
															"border-color: rgb(170, 0, 0);")
		self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_6.setObjectName("line_6")
		self.line_7 = QtWidgets.QFrame(self.frame_3)
		self.line_7.setGeometry(QtCore.QRect(340, 0, 3, 61))
		self.line_7.setStyleSheet("background-color: rgb(170, 0, 0);\n"
															"border-color: rgb(170, 0, 0);")
		self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_7.setObjectName("line_7")
		self.line_8 = QtWidgets.QFrame(self.frame_3)
		self.line_8.setGeometry(QtCore.QRect(10, 200, 391, 16))
		self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_8.setObjectName("line_8")
		self.line_4 = QtWidgets.QFrame(self.frame_3)
		self.line_4.setGeometry(QtCore.QRect(130, 60, 3, 61))
		self.line_4.setStyleSheet("background-color: rgb(170, 0, 0);")
		self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_4.setObjectName("line_4")
		self.label_36 = QtWidgets.QLabel(self.frame_3)
		self.label_36.setGeometry(QtCore.QRect(10, 230, 61, 16))
		self.label_36.setObjectName("label_36")
		self.label_37 = QtWidgets.QLabel(self.frame_3)
		self.label_37.setGeometry(QtCore.QRect(110, 230, 61, 16))
		self.label_37.setObjectName("label_37")
		self.label_38 = QtWidgets.QLabel(self.frame_3)
		self.label_38.setGeometry(QtCore.QRect(210, 230, 61, 16))
		self.label_38.setObjectName("label_38")
		self.label_39 = QtWidgets.QLabel(self.frame_3)
		self.label_39.setGeometry(QtCore.QRect(320, 230, 61, 16))
		self.label_39.setObjectName("label_39")
		self.line_9 = QtWidgets.QFrame(self.frame_3)
		self.line_9.setGeometry(QtCore.QRect(20, 200, 16, 21))
		self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_9.setObjectName("line_9")
		self.line_10 = QtWidgets.QFrame(self.frame_3)
		self.line_10.setGeometry(QtCore.QRect(120, 200, 16, 21))
		self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_10.setObjectName("line_10")
		self.line_11 = QtWidgets.QFrame(self.frame_3)
		self.line_11.setGeometry(QtCore.QRect(220, 200, 16, 21))
		self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_11.setObjectName("line_11")
		self.line_12 = QtWidgets.QFrame(self.frame_3)
		self.line_12.setGeometry(QtCore.QRect(330, 200, 16, 21))
		self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_12.setObjectName("line_12")
		self.gridLayout_8.addWidget(self.frame_3, 0, 1, 1, 1)
		self.gridLayout_6.addWidget(self.timeline_footer, 1, 0, 1, 1, QtCore.Qt.AlignTop)
		self.timeline_header = QtWidgets.QFrame(self.scrollAreaWidgetContents)
		self.timeline_header.setAutoFillBackground(False)
		self.timeline_header.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.timeline_header.setFrameShadow(QtWidgets.QFrame.Plain)
		self.timeline_header.setObjectName("timeline_header")
		self.gridLayout_4 = QtWidgets.QGridLayout(self.timeline_header)
		self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_4.setHorizontalSpacing(6)
		self.gridLayout_4.setObjectName("gridLayout_4")
		self.timeline_metadata = QtWidgets.QFrame(self.timeline_header)
		self.timeline_metadata.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.timeline_metadata.setFrameShadow(QtWidgets.QFrame.Plain)
		self.timeline_metadata.setObjectName("timeline_metadata")
		self.gridLayout_7 = QtWidgets.QGridLayout(self.timeline_metadata)
		self.gridLayout_7.setObjectName("gridLayout_7")
		self.label_31 = QtWidgets.QLabel(self.timeline_metadata)
		self.label_31.setObjectName("label_31")
		self.gridLayout_7.addWidget(self.label_31, 0, 0, 1, 1)
		self.label_32 = QtWidgets.QLabel(self.timeline_metadata)
		self.label_32.setObjectName("label_32")
		self.gridLayout_7.addWidget(self.label_32, 1, 0, 1, 1)
		self.lineEdit = QtWidgets.QLineEdit(self.timeline_metadata)
		self.lineEdit.setText("")
		self.lineEdit.setObjectName("lineEdit")
		self.gridLayout_7.addWidget(self.lineEdit, 1, 1, 1, 1)
		self.label_33 = QtWidgets.QLabel(self.timeline_metadata)
		self.label_33.setObjectName("label_33")
		self.gridLayout_7.addWidget(self.label_33, 2, 0, 1, 1)
		self.comboBox = QtWidgets.QComboBox(self.timeline_metadata)
		self.comboBox.setObjectName("comboBox")
		self.comboBox.addItem("")
		self.gridLayout_7.addWidget(self.comboBox, 2, 1, 1, 1)
		self.label_34 = QtWidgets.QLabel(self.timeline_metadata)
		self.label_34.setObjectName("label_34")
		self.gridLayout_7.addWidget(self.label_34, 3, 0, 1, 1)
		self.lineEdit_2 = QtWidgets.QLineEdit(self.timeline_metadata)
		self.lineEdit_2.setObjectName("lineEdit_2")
		self.gridLayout_7.addWidget(self.lineEdit_2, 3, 1, 1, 1)
		self.gridLayout_4.addWidget(self.timeline_metadata, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
		self.timeline_title = QtWidgets.QFrame(self.timeline_header)
		self.timeline_title.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.timeline_title.setFrameShadow(QtWidgets.QFrame.Raised)
		self.timeline_title.setObjectName("timeline_title")
		self.gridLayout_5 = QtWidgets.QGridLayout(self.timeline_title)
		self.gridLayout_5.setObjectName("gridLayout_5")
		self.label_5 = QtWidgets.QLabel(self.timeline_title)
		self.label_5.setObjectName("label_5")
		self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
		self.label_7 = QtWidgets.QLabel(self.timeline_title)
		self.label_7.setObjectName("label_7")
		self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
		self.lineEdit_3 = QtWidgets.QLineEdit(self.timeline_title)
		self.lineEdit_3.setObjectName("lineEdit_3")
		self.gridLayout_5.addWidget(self.lineEdit_3, 1, 1, 1, 1)
		self.frame_2 = QtWidgets.QFrame(self.timeline_title)
		self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_2.setObjectName("frame_2")
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
		self.pushButton_2.setObjectName("pushButton_2")
		self.horizontalLayout_3.addWidget(self.pushButton_2)
		self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
		self.pushButton_3.setObjectName("pushButton_3")
		self.horizontalLayout_3.addWidget(self.pushButton_3)
		self.gridLayout_5.addWidget(self.frame_2, 2, 1, 1, 1)
		self.label_40 = QtWidgets.QLabel(self.timeline_title)
		self.label_40.setObjectName("label_40")
		self.gridLayout_5.addWidget(self.label_40, 2, 0, 1, 1)
		self.gridLayout_4.addWidget(self.timeline_title, 0, 1, 1, 1, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
		self.gridLayout_6.addWidget(self.timeline_header, 0, 0, 1, 1, QtCore.Qt.AlignTop)
		self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
		self.gridLayout_11.addWidget(self.scrollArea_2, 0, 1, 1, 1)
		self.visualization_tabs.addTab(self.timeline, "")
		self.annotation = QtWidgets.QWidget()
		self.annotation.setObjectName("annotation")
		self.formLayout = QtWidgets.QFormLayout(self.annotation)
		self.formLayout.setObjectName("formLayout")
		self.visualization_table = QtWidgets.QTableWidget(self.annotation)
		self.visualization_table.setShowGrid(True)
		self.visualization_table.setGridStyle(QtCore.Qt.NoPen)
		self.visualization_table.setObjectName("visualization_table")
		self.visualization_table.setColumnCount(4)
		self.visualization_table.setRowCount(2)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setVerticalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setItem(0, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setItem(0, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setItem(0, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setItem(0, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setItem(1, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setItem(1, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setItem(1, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.visualization_table.setItem(1, 3, item)
		self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.visualization_table)
		self.plainTextEdit = QtWidgets.QPlainTextEdit(self.annotation)
		self.plainTextEdit.setObjectName("plainTextEdit")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.plainTextEdit)
		self.pushButton_4 = QtWidgets.QPushButton(self.annotation)
		self.pushButton_4.setObjectName("pushButton_4")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_4)
		self.visualization_tabs.addTab(self.annotation, "")
		self.gridLayout_9.addWidget(self.visualization_tabs, 0, 1, 1, 1)
		self.toolBox_accordion.addItem(self.visualization_accordion_20, "")
		self.script_accordion_16 = QtWidgets.QWidget()
		self.script_accordion_16.setGeometry(QtCore.QRect(0, 0, 548, 197))
		self.script_accordion_16.setObjectName("script_accordion_16")
		self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.script_accordion_16)
		self.verticalLayout_8.setObjectName("verticalLayout_8")
		self.table_tag_2 = QtWidgets.QTableWidget(self.script_accordion_16)
		self.table_tag_2.setAcceptDrops(False)
		self.table_tag_2.setEditTriggers(
				QtWidgets.QAbstractItemView.AnyKeyPressed | QtWidgets.QAbstractItemView.DoubleClicked)
		self.table_tag_2.setAlternatingRowColors(True)
		self.table_tag_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
		self.table_tag_2.setCornerButtonEnabled(True)
		self.table_tag_2.setRowCount(10)
		self.table_tag_2.setObjectName("table_tag_2")
		self.table_tag_2.setColumnCount(7)
		item = QtWidgets.QTableWidgetItem()
		self.table_tag_2.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.table_tag_2.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.table_tag_2.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.table_tag_2.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.table_tag_2.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.table_tag_2.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		self.table_tag_2.setHorizontalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.table_tag_2.setItem(0, 0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(0, 1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable)
		self.table_tag_2.setItem(0, 3, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(0, 4, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.table_tag_2.setItem(1, 0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(1, 1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable)
		self.table_tag_2.setItem(1, 3, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(1, 4, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.table_tag_2.setItem(2, 0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(2, 1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable)
		self.table_tag_2.setItem(2, 3, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(2, 4, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.table_tag_2.setItem(3, 0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(3, 1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable)
		self.table_tag_2.setItem(3, 3, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(3, 4, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.table_tag_2.setItem(4, 0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(4, 1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable)
		self.table_tag_2.setItem(4, 3, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(4, 4, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.table_tag_2.setItem(5, 0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(5, 1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable)
		self.table_tag_2.setItem(5, 3, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(5, 4, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.table_tag_2.setItem(6, 0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(6, 1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable)
		self.table_tag_2.setItem(6, 3, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(6, 4, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.table_tag_2.setItem(7, 0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(7, 1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable)
		self.table_tag_2.setItem(7, 3, item)
		item = QtWidgets.QTableWidgetItem()
		item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsEnabled)
		self.table_tag_2.setItem(7, 4, item)
		self.table_tag_2.horizontalHeader().setCascadingSectionResizes(True)
		self.table_tag_2.horizontalHeader().setDefaultSectionSize(150)
		self.table_tag_2.horizontalHeader().setMinimumSectionSize(20)
		self.table_tag_2.horizontalHeader().setSortIndicatorShown(True)
		self.table_tag_2.horizontalHeader().setStretchLastSection(True)
		self.table_tag_2.verticalHeader().setVisible(False)
		self.table_tag_2.verticalHeader().setCascadingSectionResizes(True)
		self.table_tag_2.verticalHeader().setSortIndicatorShown(True)
		self.verticalLayout_8.addWidget(self.table_tag_2)
		self.frame_13 = QtWidgets.QFrame(self.script_accordion_16)
		self.frame_13.setMaximumSize(QtCore.QSize(16777215, 111))
		self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_13.setObjectName("frame_13")
		self.gridLayout_35 = QtWidgets.QGridLayout(self.frame_13)
		self.gridLayout_35.setObjectName("gridLayout_35")
		self.pushButton_7 = QtWidgets.QPushButton(self.frame_13)
		self.pushButton_7.setObjectName("pushButton_7")
		self.gridLayout_35.addWidget(self.pushButton_7, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
		self.pushButton_8 = QtWidgets.QPushButton(self.frame_13)
		self.pushButton_8.setObjectName("pushButton_8")
		self.gridLayout_35.addWidget(self.pushButton_8, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
		self.pushButton_9 = QtWidgets.QPushButton(self.frame_13)
		self.pushButton_9.setObjectName("pushButton_9")
		self.gridLayout_35.addWidget(self.pushButton_9, 0, 2, 1, 1, QtCore.Qt.AlignLeft)
		self.pushButton_11 = QtWidgets.QPushButton(self.frame_13)
		self.pushButton_11.setObjectName("pushButton_11")
		self.gridLayout_35.addWidget(self.pushButton_11, 0, 3, 1, 1, QtCore.Qt.AlignLeft)
		self.pushButton_10 = QtWidgets.QPushButton(self.frame_13)
		self.pushButton_10.setObjectName("pushButton_10")
		self.gridLayout_35.addWidget(self.pushButton_10, 0, 4, 1, 1, QtCore.Qt.AlignLeft)
		self.pushButton_12 = QtWidgets.QPushButton(self.frame_13)
		self.pushButton_12.setObjectName("pushButton_12")
		self.gridLayout_35.addWidget(self.pushButton_12, 0, 5, 1, 1, QtCore.Qt.AlignLeft)
		self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame_13)
		self.plainTextEdit_2.setReadOnly(True)
		self.plainTextEdit_2.setBackgroundVisible(False)
		self.plainTextEdit_2.setObjectName("plainTextEdit_2")
		self.gridLayout_35.addWidget(self.plainTextEdit_2, 1, 0, 1, 1)
		self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.frame_13)
		self.plainTextEdit_3.setReadOnly(True)
		self.plainTextEdit_3.setObjectName("plainTextEdit_3")
		self.gridLayout_35.addWidget(self.plainTextEdit_3, 1, 1, 1, 1)
		self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.frame_13)
		self.plainTextEdit_5.setReadOnly(True)
		self.plainTextEdit_5.setObjectName("plainTextEdit_5")
		self.gridLayout_35.addWidget(self.plainTextEdit_5, 1, 2, 1, 1)
		self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.frame_13)
		self.plainTextEdit_6.setReadOnly(True)
		self.plainTextEdit_6.setObjectName("plainTextEdit_6")
		self.gridLayout_35.addWidget(self.plainTextEdit_6, 1, 3, 1, 1)
		self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.frame_13)
		self.plainTextEdit_7.setReadOnly(True)
		self.plainTextEdit_7.setObjectName("plainTextEdit_7")
		self.gridLayout_35.addWidget(self.plainTextEdit_7, 1, 4, 1, 1)
		self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.frame_13)
		self.plainTextEdit_4.setReadOnly(True)
		self.plainTextEdit_4.setObjectName("plainTextEdit_4")
		self.gridLayout_35.addWidget(self.plainTextEdit_4, 1, 5, 1, 1)
		self.verticalLayout_8.addWidget(self.frame_13)
		self.toolBox_accordion.addItem(self.script_accordion_16, "")
		self.history_accordion_16 = QtWidgets.QWidget()
		self.history_accordion_16.setGeometry(QtCore.QRect(0, 0, 141, 113))
		self.history_accordion_16.setObjectName("history_accordion_16")
		self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.history_accordion_16)
		self.verticalLayout_9.setObjectName("verticalLayout_9")
		self.history_table = QtWidgets.QTableWidget(self.history_accordion_16)
		self.history_table.setStyleSheet("")
		self.history_table.setAutoScrollMargin(16)
		self.history_table.setDragEnabled(True)
		self.history_table.setAlternatingRowColors(True)
		self.history_table.setTextElideMode(QtCore.Qt.ElideNone)
		self.history_table.setObjectName("history_table")
		self.history_table.setColumnCount(6)
		self.history_table.setRowCount(6)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setVerticalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setVerticalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setVerticalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setVerticalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setVerticalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setStyleStrategy(QtGui.QFont.PreferAntialias)
		item.setFont(font)
		item.setCheckState(QtCore.Qt.Unchecked)
		self.history_table.setItem(0, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(0, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(0, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(0, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(0, 4, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(0, 5, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.history_table.setItem(1, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(1, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(1, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(1, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(1, 4, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(1, 5, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.history_table.setItem(2, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(2, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(2, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(2, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(2, 4, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(2, 5, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.history_table.setItem(3, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(3, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(3, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(3, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(3, 4, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(3, 5, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.history_table.setItem(4, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(4, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(4, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(4, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(4, 4, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(4, 5, item)
		item = QtWidgets.QTableWidgetItem()
		item.setCheckState(QtCore.Qt.Unchecked)
		self.history_table.setItem(5, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(5, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(5, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(5, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(5, 4, item)
		item = QtWidgets.QTableWidgetItem()
		self.history_table.setItem(5, 5, item)
		self.history_table.horizontalHeader().setCascadingSectionResizes(True)
		self.history_table.horizontalHeader().setDefaultSectionSize(170)
		self.history_table.horizontalHeader().setStretchLastSection(True)
		self.verticalLayout_9.addWidget(self.history_table)
		self.pushButton_13 = QtWidgets.QPushButton(self.history_accordion_16)
		self.pushButton_13.setObjectName("pushButton_13")
		self.verticalLayout_9.addWidget(self.pushButton_13, 0, QtCore.Qt.AlignLeft)
		self.toolBox_accordion.addItem(self.history_accordion_16, "")
		self.log_accordion_16 = QtWidgets.QWidget()
		self.log_accordion_16.setGeometry(QtCore.QRect(0, 0, 92, 80))
		self.log_accordion_16.setObjectName("log_accordion_16")
		self.gridLayout_36 = QtWidgets.QGridLayout(self.log_accordion_16)
		self.gridLayout_36.setObjectName("gridLayout_36")
		self.tableWidget_40 = QtWidgets.QTableWidget(self.log_accordion_16)
		self.tableWidget_40.setAlternatingRowColors(True)
		self.tableWidget_40.setObjectName("tableWidget_40")
		self.tableWidget_40.setColumnCount(5)
		self.tableWidget_40.setRowCount(5)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setVerticalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setVerticalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setVerticalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setVerticalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(0, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(0, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(0, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(0, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(0, 4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(1, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(1, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(1, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(1, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(1, 4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(2, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(2, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(2, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(2, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(2, 4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(3, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(3, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(3, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(3, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(3, 4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(4, 0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(4, 1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(4, 2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(4, 3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_40.setItem(4, 4, item)
		self.tableWidget_40.horizontalHeader().setDefaultSectionSize(170)
		self.tableWidget_40.horizontalHeader().setMinimumSectionSize(50)
		self.tableWidget_40.horizontalHeader().setStretchLastSection(True)
		self.gridLayout_36.addWidget(self.tableWidget_40, 0, 0, 1, 1)
		self.toolBox_accordion.addItem(self.log_accordion_16, "")
		self.verticalLayout_4.addWidget(self.toolBox_accordion)
		self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
		self.gridLayout_tab_1.addWidget(self.scrollArea, 0, 0, 1, 1)

		_translate = QtCore.QCoreApplication.translate


		self.label_10.setText(_translate("MainWindow", "Search"))
		self.search_expression_bar.setPlaceholderText(_translate("MainWindow", "Search Expression"))
		self.label_8.setText(_translate("MainWindow", "Tag"))
		self.search_tag.setItemText(0, _translate("MainWindow", "Tag"))
		self.search_tag.setItemText(1, _translate("MainWindow", "Tag"))
		self.search_button.setText(_translate("MainWindow", "Search"))
		self.universalRecord.setText(_translate("MainWindow", "Record On"))


		self.mac_dropdown.setItemText(0, _translate("MainWindow", "7D:93:74:82:7B:71"))
		self.mac_dropdown.setItemText(1, _translate("MainWindow", "7D:93:74:82:7B:71"))
		self.mac_dropdown.setItemText(2, _translate("MainWindow", "7D:93:74:82:7B:71"))

		self.label_filters.setText(_translate("MainWindow", "Filters"))
		self.label_value_filter.setText(_translate("MainWindow", "Value"))

		self.label_user_profile.setText(_translate("MainWindow", "User Profile"))
		self.label_ip_address.setText(_translate("MainWindow", "IP Address"))
		self.label_mac_address.setText(_translate("MainWindow", "MAC Address"))
		self.label_type.setText(_translate("MainWindow", "Type"))
		self.label_value_type.setText(_translate("MainWindow", "Value"))


		self.label_all_artifacts.setText(_translate("MainWindow", "All Arifact Types"))
		self.label_screenshot.setText(_translate("MainWindow", "Still Screenshot"))
		self.label_video.setText(_translate("MainWindow", "Video"))
		self.label_network.setText(_translate("MainWindow", "Network Packet"))
		self.label_process.setText(_translate("MainWindow", "Process"))
		self.label_keystroke.setText(_translate("MainWindow", "Keystroke"))
		self.label_mouse_action.setText(_translate("MainWindow", "Mouse Action"))
		self.label_window_history.setText(_translate("MainWindow", "Window History"))
		self.label_system_call.setText(_translate("MainWindow", "System Call"))
		self.label_history.setText(_translate("MainWindow", "History"))
		self.label_log.setText(_translate("MainWindow", "Log"))


		self.label_date_time.setText(_translate("MainWindow", "Date and Time"))
		self.label_value_date_time.setText(_translate("MainWindow", "Value"))
		self.label_start_date.setText(_translate("MainWindow", "Start Date"))
		self.label_start_time.setText(_translate("MainWindow", "Start Time"))
		self.label_end_date.setText(_translate("MainWindow", "End Date"))
		self.label_end_time.setText(_translate("MainWindow", "End Time"))


		self.ip_dropdown.setItemText(0, _translate("MainWindow", "195.273.25.4"))
		self.ip_dropdown.setItemText(1, _translate("MainWindow", "195.273.25.4"))
		self.ip_dropdown.setItemText(2, _translate("MainWindow", "195.273.25.4"))

		self.label_9.setText(_translate("MainWindow", "AVERT RESULT"))
		self.exportButton.setText(_translate("MainWindow", "Export"))
		self.pushButton_15.setText(_translate("MainWindow", "Delete"))
		self.pushButton_16.setText(_translate("MainWindow", "Add Selected to Script Creation"))


		

		self.toolBox_accordion.setItemText(self.toolBox_accordion.indexOf(self.detailed_view_accordion.get_accordion()),
																_translate("MainWindow", "Detailed View of Selected Artifact"))
		self.radioButton_2.setText(_translate("MainWindow", "Bar Graph"))
		self.radioButton_4.setText(_translate("MainWindow", "Timeline"))
		self.radioButton.setText(_translate("MainWindow", "Pie Chart"))
		self.pushButton_5.setText(_translate("MainWindow", "Generate"))
		self.pushButton_6.setText(_translate("MainWindow", "Export"))
		self.visualization_tabs.setTabText(self.visualization_tabs.indexOf(self.type), _translate("MainWindow", "Type"))
		self.label_91.setText(_translate("MainWindow", "Title"))
		self.label_90.setText(_translate("MainWindow", "Pie Chart Metadata"))
		self.label_92.setText(_translate("MainWindow", "Visualization Result"))
		self.label_93.setText(_translate("MainWindow", "Pie Chart Title"))
		self.visualization_tabs.setTabText(self.visualization_tabs.indexOf(self.pie_chart),
																			_translate("MainWindow", "Pie Chart"))
		self.visualization_tabs.setTabText(self.visualization_tabs.indexOf(self.bar_graph),
																			_translate("MainWindow", "Bar Graph"))
		self.label_35.setText(_translate("MainWindow", "Artifact Key"))
		__sortingEnabled = self.listWidget.isSortingEnabled()
		self.listWidget.setSortingEnabled(False)
		item = self.listWidget.item(0)
		item.setText(_translate("MainWindow", "* Still Screenshot"))
		item = self.listWidget.item(1)
		item.setText(_translate("MainWindow", "* Video"))
		item = self.listWidget.item(2)
		item.setText(_translate("MainWindow", "* Network Packet"))
		item = self.listWidget.item(3)
		item.setText(_translate("MainWindow", "* Process"))
		item = self.listWidget.item(4)
		item.setText(_translate("MainWindow", "* Keystroke"))
		item = self.listWidget.item(5)
		item.setText(_translate("MainWindow", "* Mouse Action"))
		item = self.listWidget.item(6)
		item.setText(_translate("MainWindow", "* Window History"))
		item = self.listWidget.item(7)
		item.setText(_translate("MainWindow", "* System Call"))
		self.listWidget.setSortingEnabled(__sortingEnabled)
		self.label_36.setText(_translate("MainWindow", "9/11/2021"))
		self.label_37.setText(_translate("MainWindow", "9/13/2021"))
		self.label_38.setText(_translate("MainWindow", "9/15/2021"))
		self.label_39.setText(_translate("MainWindow", "9/18/2021"))
		self.label_31.setText(_translate("MainWindow", "Timeline Metadata"))
		self.label_32.setText(_translate("MainWindow", "Title"))
		self.label_33.setText(_translate("MainWindow", "Tick Interval Unit"))
		self.comboBox.setItemText(0, _translate("MainWindow", "Unit"))
		self.label_34.setText(_translate("MainWindow", "TIck Interval Value"))
		self.label_5.setText(_translate("MainWindow", "Visualization Result"))
		self.label_7.setText(_translate("MainWindow", "Timeline Title"))
		self.pushButton_2.setText(_translate("MainWindow", "+"))
		self.pushButton_3.setText(_translate("MainWindow", "-"))
		self.label_40.setText(_translate("MainWindow", "Zoom"))
		self.visualization_tabs.setTabText(self.visualization_tabs.indexOf(self.timeline),
																			_translate("MainWindow", "Timeline"))
		self.visualization_table.setSortingEnabled(False)
		item = self.visualization_table.verticalHeaderItem(0)
		item.setText(_translate("MainWindow", "1"))
		item = self.visualization_table.verticalHeaderItem(1)
		item.setText(_translate("MainWindow", "2"))
		item = self.visualization_table.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "Timestamp"))
		item = self.visualization_table.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "IP Address"))
		item = self.visualization_table.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "MAC Address"))
		item = self.visualization_table.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "Description"))
		__sortingEnabled = self.visualization_table.isSortingEnabled()
		self.visualization_table.setSortingEnabled(False)
		item = self.visualization_table.item(0, 0)
		item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
		item = self.visualization_table.item(0, 1)
		item.setText(_translate("MainWindow", "125.42.0.1"))
		item = self.visualization_table.item(0, 2)
		item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
		item = self.visualization_table.item(0, 3)
		item.setText(_translate("MainWindow", "Lorem ipsum"))
		item = self.visualization_table.item(1, 0)
		item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
		item = self.visualization_table.item(1, 1)
		item.setText(_translate("MainWindow", "125.42.0.1"))
		item = self.visualization_table.item(1, 2)
		item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
		item = self.visualization_table.item(1, 3)
		item.setText(_translate("MainWindow", "Lorem ipsum"))
		self.visualization_table.setSortingEnabled(__sortingEnabled)
		self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "Annotation"))
		self.pushButton_4.setText(_translate("MainWindow", "Add"))
		self.visualization_tabs.setTabText(self.visualization_tabs.indexOf(self.annotation),
																			_translate("MainWindow", "Annotation"))
		self.toolBox_accordion.setItemText(self.toolBox_accordion.indexOf(self.visualization_accordion_20),
																_translate("MainWindow", "Visualization"))
		item = self.table_tag_2.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "Select"))
		item = self.table_tag_2.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "Added Artifact"))
		item = self.table_tag_2.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "Time Stamp"))
		item = self.table_tag_2.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "Artifact Type"))
		item = self.table_tag_2.horizontalHeaderItem(4)
		item.setText(_translate("MainWindow", "Tag"))
		item = self.table_tag_2.horizontalHeaderItem(5)
		item.setText(_translate("MainWindow", "MAC Address"))
		item = self.table_tag_2.horizontalHeaderItem(6)
		item.setText(_translate("MainWindow", "Description"))
		__sortingEnabled = self.table_tag_2.isSortingEnabled()
		self.table_tag_2.setSortingEnabled(False)
		self.table_tag_2.setSortingEnabled(__sortingEnabled)
		self.pushButton_7.setText(_translate("MainWindow", "Up"))
		self.pushButton_8.setText(_translate("MainWindow", "Down"))
		self.pushButton_9.setText(_translate("MainWindow", "Remove"))
		self.pushButton_11.setText(_translate("MainWindow", "Generate"))
		self.pushButton_10.setText(_translate("MainWindow", "Export"))
		self.pushButton_12.setText(_translate("MainWindow", "Preview"))
		self.plainTextEdit_2.setPlainText(_translate("MainWindow", "Move Artifact Up"))
		self.plainTextEdit_3.setPlainText(_translate("MainWindow", "Move Artifact Down"))
		self.plainTextEdit_5.setPlainText(_translate("MainWindow", "Remove Artifact from Script Creation Table"))
		self.plainTextEdit_6.setPlainText(_translate("MainWindow", "Generate Script"))
		self.plainTextEdit_7.setPlainText(_translate("MainWindow", "Export Script"))
		self.plainTextEdit_4.setPlainText(_translate("MainWindow", "Generate Script Preview Window"))
		self.toolBox_accordion.setItemText(self.toolBox_accordion.indexOf(self.script_accordion_16),
																_translate("MainWindow", "Script"))
		self.history_table.setSortingEnabled(True)
		item = self.history_table.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "Select"))
		item = self.history_table.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "Timestamp"))
		item = self.history_table.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "Expression Type"))
		item = self.history_table.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "IP Address"))
		item = self.history_table.horizontalHeaderItem(4)
		item.setText(_translate("MainWindow", "MAC Address"))
		item = self.history_table.horizontalHeaderItem(5)
		item.setText(_translate("MainWindow", "Expression"))
		__sortingEnabled = self.history_table.isSortingEnabled()
		self.history_table.setSortingEnabled(False)
		item = self.history_table.item(0, 1)
		item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
		item = self.history_table.item(0, 2)
		item.setText(_translate("MainWindow", "Type"))
		item = self.history_table.item(0, 3)
		item.setText(_translate("MainWindow", "125.42.0.1"))
		item = self.history_table.item(0, 4)
		item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
		item = self.history_table.item(0, 5)
		item.setText(_translate("MainWindow", "Sample Expression"))
		item = self.history_table.item(1, 1)
		item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
		item = self.history_table.item(1, 2)
		item.setText(_translate("MainWindow", "Type"))
		item = self.history_table.item(1, 3)
		item.setText(_translate("MainWindow", "125.42.0.1"))
		item = self.history_table.item(1, 4)
		item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
		item = self.history_table.item(1, 5)
		item.setText(_translate("MainWindow", "Sample Expression"))
		item = self.history_table.item(2, 1)
		item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
		item = self.history_table.item(2, 2)
		item.setText(_translate("MainWindow", "Type"))
		item = self.history_table.item(2, 3)
		item.setText(_translate("MainWindow", "125.42.0.1"))
		item = self.history_table.item(2, 4)
		item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
		item = self.history_table.item(2, 5)
		item.setText(_translate("MainWindow", "Sample Expression"))
		item = self.history_table.item(3, 1)
		item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
		item = self.history_table.item(3, 2)
		item.setText(_translate("MainWindow", "Type"))
		item = self.history_table.item(3, 3)
		item.setText(_translate("MainWindow", "125.42.0.1"))
		item = self.history_table.item(3, 4)
		item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
		item = self.history_table.item(3, 5)
		item.setText(_translate("MainWindow", "Sample Expression"))
		item = self.history_table.item(4, 1)
		item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
		item = self.history_table.item(4, 2)
		item.setText(_translate("MainWindow", "Type"))
		item = self.history_table.item(4, 3)
		item.setText(_translate("MainWindow", "125.42.0.1"))
		item = self.history_table.item(4, 4)
		item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
		item = self.history_table.item(4, 5)
		item.setText(_translate("MainWindow", "Sample Expression"))
		item = self.history_table.item(5, 1)
		item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
		item = self.history_table.item(5, 2)
		item.setText(_translate("MainWindow", "Type"))
		item = self.history_table.item(5, 3)
		item.setText(_translate("MainWindow", "125.42.0.1"))
		item = self.history_table.item(5, 4)
		item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
		item = self.history_table.item(5, 5)
		item.setText(_translate("MainWindow", "Sample Expression"))
		self.history_table.setSortingEnabled(__sortingEnabled)
		self.pushButton_13.setText(_translate("MainWindow", "Apply Expression"))
		self.toolBox_accordion.setItemText(self.toolBox_accordion.indexOf(self.history_accordion_16),
																_translate("MainWindow", "History"))
		self.tableWidget_40.setSortingEnabled(True)
		item = self.tableWidget_40.verticalHeaderItem(0)
		item.setText(_translate("MainWindow", "1"))
		item = self.tableWidget_40.verticalHeaderItem(1)
		item.setText(_translate("MainWindow", "2"))
		item = self.tableWidget_40.verticalHeaderItem(2)
		item.setText(_translate("MainWindow", "3"))
		item = self.tableWidget_40.verticalHeaderItem(3)
		item.setText(_translate("MainWindow", "4"))
		item = self.tableWidget_40.verticalHeaderItem(4)
		item.setText(_translate("MainWindow", "5"))
		item = self.tableWidget_40.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "Time Stamp"))
		item = self.tableWidget_40.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "Artifact Type"))
		item = self.tableWidget_40.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "IP Address"))
		item = self.tableWidget_40.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "MAC Address"))
		item = self.tableWidget_40.horizontalHeaderItem(4)
		item.setText(_translate("MainWindow", "Action Preformed on Artifact"))
		__sortingEnabled = self.tableWidget_40.isSortingEnabled()
		self.tableWidget_40.setSortingEnabled(False)
		item = self.tableWidget_40.item(0, 0)
		item.setText(_translate("MainWindow", "2020-9-11 06:46:00"))
		item = self.tableWidget_40.item(0, 1)
		item.setText(_translate("MainWindow", "Screenshot"))
		item = self.tableWidget_40.item(0, 2)
		item.setText(_translate("MainWindow", "127.0.0.1"))
		item = self.tableWidget_40.item(0, 3)
		item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
		item = self.tableWidget_40.item(0, 4)
		item.setText(_translate("MainWindow", "Deleted"))
		item = self.tableWidget_40.item(1, 0)
		item.setText(_translate("MainWindow", "2020-9-12 07:46:00"))
		item = self.tableWidget_40.item(1, 1)
		item.setText(_translate("MainWindow", "Video"))
		item = self.tableWidget_40.item(1, 2)
		item.setText(_translate("MainWindow", "127.0.0.1"))
		item = self.tableWidget_40.item(1, 3)
		item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
		item = self.tableWidget_40.item(1, 4)
		item.setText(_translate("MainWindow", "Deleted"))
		item = self.tableWidget_40.item(2, 0)
		item.setText(_translate("MainWindow", "2020-9-13 08:46:00"))
		item = self.tableWidget_40.item(2, 1)
		item.setText(_translate("MainWindow", "Process"))
		item = self.tableWidget_40.item(2, 2)
		item.setText(_translate("MainWindow", "127.0.0.1"))
		item = self.tableWidget_40.item(2, 3)
		item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
		item = self.tableWidget_40.item(2, 4)
		item.setText(_translate("MainWindow", "Captured"))
		item = self.tableWidget_40.item(3, 0)
		item.setText(_translate("MainWindow", "2020-9-14 09:46:00"))
		item = self.tableWidget_40.item(3, 1)
		item.setText(_translate("MainWindow", "System Call"))
		item = self.tableWidget_40.item(3, 2)
		item.setText(_translate("MainWindow", "127.0.0.1"))
		item = self.tableWidget_40.item(3, 3)
		item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
		item = self.tableWidget_40.item(3, 4)
		item.setText(_translate("MainWindow", "Captured"))
		item = self.tableWidget_40.item(4, 0)
		item.setText(_translate("MainWindow", "2020-9-15 10:46:00"))
		item = self.tableWidget_40.item(4, 1)
		item.setText(_translate("MainWindow", "Key Stroke"))
		item = self.tableWidget_40.item(4, 2)
		item.setText(_translate("MainWindow", "127.0.0.1"))
		item = self.tableWidget_40.item(4, 3)
		item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
		item = self.tableWidget_40.item(4, 4)
		item.setText(_translate("MainWindow", "Captured"))
		self.tableWidget_40.setSortingEnabled(__sortingEnabled)
		self.toolBox_accordion.setItemText(self.toolBox_accordion.indexOf(self.log_accordion_16),
																_translate("MainWindow", "Log Content"))

	def get_tab(self):
		return self.tab_1
