from PyQt5 import QtWidgets, QtCore, QtGui
from view.components import result_table, annotation_table, bar_graph


class Log_Accordion:
    def __init__(self):
        self.log_accordion = QtWidgets.QWidget()
        self.log_accordion.setGeometry(QtCore.QRect(0, 0, 92, 80))
        self.log_accordion.setObjectName("log_accordion")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.log_accordion)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.tableWidget_40 = QtWidgets.QTableWidget(self.log_accordion)
        self.tableWidget_40.setAlternatingRowColors(True)
        self.tableWidget_40.setObjectName("tableWidget_40")
        self.tableWidget_40.setColumnCount(5)
        self.tableWidget_40.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(4, 4, item)
        self.tableWidget_40.horizontalHeader().setDefaultSectionSize(170)
        self.tableWidget_40.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_40.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_36.addWidget(self.tableWidget_40, 0, 0, 1, 1)

        """retranslateUi"""
        _translate = QtCore.QCoreApplication.translate
        self.tableWidget_40.setSortingEnabled(True)
        item = self.tableWidget_40.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_40.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_40.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_40.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_40.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_40.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time Stamp"))
        item = self.tableWidget_40.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Artifact Type"))
        item = self.tableWidget_40.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget_40.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MAC Address"))
        item = self.tableWidget_40.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Action Preformed on Artifact"))
        __sortingEnabled = self.tableWidget_40.isSortingEnabled()
        self.tableWidget_40.setSortingEnabled(False)
        item = self.tableWidget_40.item(0, 0)
        item.setText(_translate("MainWindow", "2020-9-11 06:46:00"))
        item = self.tableWidget_40.item(0, 1)
        item.setText(_translate("MainWindow", "Screenshot"))
        item = self.tableWidget_40.item(0, 2)
        item.setText(_translate("MainWindow", "127.0.0.1"))
        item = self.tableWidget_40.item(0, 3)
        item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
        item = self.tableWidget_40.item(0, 4)
        item.setText(_translate("MainWindow", "Deleted"))
        item = self.tableWidget_40.item(1, 0)
        item.setText(_translate("MainWindow", "2020-9-12 07:46:00"))
        item = self.tableWidget_40.item(1, 1)
        item.setText(_translate("MainWindow", "Video"))
        item = self.tableWidget_40.item(1, 2)
        item.setText(_translate("MainWindow", "127.0.0.1"))
        item = self.tableWidget_40.item(1, 3)
        item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
        item = self.tableWidget_40.item(1, 4)
        item.setText(_translate("MainWindow", "Deleted"))
        item = self.tableWidget_40.item(2, 0)
        item.setText(_translate("MainWindow", "2020-9-13 08:46:00"))
        item = self.tableWidget_40.item(2, 1)
        item.setText(_translate("MainWindow", "Process"))
        item = self.tableWidget_40.item(2, 2)
        item.setText(_translate("MainWindow", "127.0.0.1"))
        item = self.tableWidget_40.item(2, 3)
        item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
        item = self.tableWidget_40.item(2, 4)
        item.setText(_translate("MainWindow", "Captured"))
        item = self.tableWidget_40.item(3, 0)
        item.setText(_translate("MainWindow", "2020-9-14 09:46:00"))
        item = self.tableWidget_40.item(3, 1)
        item.setText(_translate("MainWindow", "System Call"))
        item = self.tableWidget_40.item(3, 2)
        item.setText(_translate("MainWindow", "127.0.0.1"))
        item = self.tableWidget_40.item(3, 3)
        item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
        item = self.tableWidget_40.item(3, 4)
        item.setText(_translate("MainWindow", "Captured"))
        item = self.tableWidget_40.item(4, 0)
        item.setText(_translate("MainWindow", "2020-9-15 10:46:00"))
        item = self.tableWidget_40.item(4, 1)
        item.setText(_translate("MainWindow", "Key Stroke"))
        item = self.tableWidget_40.item(4, 2)
        item.setText(_translate("MainWindow", "127.0.0.1"))
        item = self.tableWidget_40.item(4, 3)
        item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
        item = self.tableWidget_40.item(4, 4)
        item.setText(_translate("MainWindow", "Captured"))
        self.tableWidget_40.setSortingEnabled(__sortingEnabled)

    def get_accordion(self):
        return self.log_accordion
