import sys, random
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QPushButton, QDialog, QTreeWidget, QTreeWidgetItem, QVBoxLayout,
                             QHBoxLayout, QFrame, QLabel, QApplication, QMainWindow)
# from PyQt6 import QtCore, QtGui, QtWidgets
# from PyQt6.QtWidgets import (QPushButton, QDialog, QTreeWidget, QTreeWidgetItem, QVBoxLayout,
#  QHBoxLayout, QFrame, QLabel,
#  QApplication, QApplication, QMainWindow, QPushButton)
from PyQt5.QtChart import QChart, QChartView, QValueAxis, QBarCategoryAxis, QBarSet, QBarSeries

from PyQt5.Qt import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.tree = QTreeWidget()
        self.tree.setHeaderHidden(True)
        self.sections = []
        self.define_sections()
        self.add_sections()

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1792, 1120)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1764, 1358))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        self.label_8.setMaximumSize(QtCore.QSize(20, 20))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_2.setMaximumSize(QtCore.QSize(150, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_1)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMaximumSize(QtCore.QSize(400, 25))
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_2.addWidget(self.textEdit_2, 2, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_3.addWidget(self.checkBox_17, 9, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_1)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 17, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_1)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_1)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_1)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 13, 0, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.tab_1)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_3.addWidget(self.timeEdit, 18, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_3.setMaximumSize(QtCore.QSize(150, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_1)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_3.addWidget(self.checkBox_15, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 18, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_3.addWidget(self.checkBox_14, 5, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_1)
        self.label_30.setStyleSheet("")
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 16, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_1)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 15, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.tab_1)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_3.addWidget(self.dateEdit, 17, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_1)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 10, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_1)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 11, 0, 1, 1)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.tab_1)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout_3.addWidget(self.timeEdit_2, 20, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_1)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 9, 0, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_3.addWidget(self.checkBox_21, 8, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_3.addWidget(self.checkBox_16, 7, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_1)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 14, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_1)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 6, 0, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_24.setText("")
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_3.addWidget(self.checkBox_24, 14, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_1)
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_3.addWidget(self.checkBox_18, 10, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_1)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 1, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_3.addWidget(self.checkBox_19, 11, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_1)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 12, 0, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_3.addWidget(self.checkBox_20, 15, 1, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_1)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_3.addWidget(self.dateEdit_2, 19, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_1)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_29.setStyleSheet("")
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 16, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_1)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 19, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_4.setMaximumSize(QtCore.QSize(150, 20))
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_3.addWidget(self.comboBox_4, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_1)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 4, 1, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_23.setText("")
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_3.addWidget(self.checkBox_23, 13, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_1)
        self.label_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_22.setText("")
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_3.addWidget(self.checkBox_22, 12, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 20, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 7, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab_1)
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 6, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.tab_1)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.toolBox_14 = QtWidgets.QToolBox(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_14.sizePolicy().hasHeightForWidth())
        self.toolBox_14.setSizePolicy(sizePolicy)
        self.toolBox_14.setMinimumSize(QtCore.QSize(0, 600))
        self.toolBox_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox_14.setObjectName("toolBox_14")
        self.detailed_view_accordion_20 = QtWidgets.QWidget()
        self.detailed_view_accordion_20.setGeometry(QtCore.QRect(0, 0, 1724, 437))
        self.detailed_view_accordion_20.setObjectName("detailed_view_accordion_20")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.detailed_view_accordion_20)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.scrollArea_53 = QtWidgets.QScrollArea(self.detailed_view_accordion_20)
        self.scrollArea_53.setWidgetResizable(True)
        self.scrollArea_53.setObjectName("scrollArea_53")
        self.scrollAreaWidgetContents_58 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_58.setGeometry(QtCore.QRect(0, 0, 1704, 417))
        self.scrollAreaWidgetContents_58.setObjectName("scrollAreaWidgetContents_58")
        self.tabWidget_32 = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_58)
        self.tabWidget_32.setGeometry(QtCore.QRect(10, 0, 1681, 401))
        self.tabWidget_32.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_32.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_32.setObjectName("tabWidget_32")
        self.tab_133 = QtWidgets.QWidget()
        self.tab_133.setObjectName("tab_133")
        self.scrollArea_54 = QtWidgets.QScrollArea(self.tab_133)
        self.scrollArea_54.setGeometry(QtCore.QRect(10, 0, 1651, 371))
        self.scrollArea_54.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_54.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_54.setWidgetResizable(True)
        self.scrollArea_54.setObjectName("scrollArea_54")
        self.scrollAreaWidgetContents_59 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_59.setGeometry(QtCore.QRect(0, 0, 1641, 369))
        self.scrollAreaWidgetContents_59.setObjectName("scrollAreaWidgetContents_59")
        self.tableWidget_38 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_59)
        self.tableWidget_38.setGeometry(QtCore.QRect(20, 10, 1591, 351))
        self.tableWidget_38.setObjectName("tableWidget_38")
        self.tableWidget_38.setColumnCount(2)
        self.tableWidget_38.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_38.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_38.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_38.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_38.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_38.setItem(0, 1, item)
        self.tableWidget_38.horizontalHeader().setDefaultSectionSize(400)
        self.scrollArea_54.setWidget(self.scrollAreaWidgetContents_59)
        self.tabWidget_32.addTab(self.tab_133, "")
        self.tab_134 = QtWidgets.QWidget()
        self.tab_134.setObjectName("tab_134")
        self.tabWidget_32.addTab(self.tab_134, "")
        self.tab_135 = QtWidgets.QWidget()
        self.tab_135.setObjectName("tab_135")
        self.tableWidget_39 = QtWidgets.QTableWidget(self.tab_135)
        self.tableWidget_39.setGeometry(QtCore.QRect(10, 10, 1651, 361))
        self.tableWidget_39.setObjectName("tableWidget_39")
        self.tableWidget_39.setColumnCount(4)
        self.tableWidget_39.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_39.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_39.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_39.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_39.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_39.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_39.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_39.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_39.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_39.setItem(0, 3, item)
        self.tableWidget_39.horizontalHeader().setDefaultSectionSize(350)
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_135)
        self.pushButton_18.setGeometry(QtCore.QRect(900, 110, 113, 32))
        self.pushButton_18.setObjectName("pushButton_18")
        self.textEdit_20 = QtWidgets.QTextEdit(self.tab_135)
        self.textEdit_20.setGeometry(QtCore.QRect(420, 70, 431, 79))
        self.textEdit_20.setObjectName("textEdit_20")
        self.tabWidget_32.addTab(self.tab_135, "")
        self.tab_136 = QtWidgets.QWidget()
        self.tab_136.setObjectName("tab_136")
        self.tabWidget_32.addTab(self.tab_136, "")
        self.scrollArea_53.setWidget(self.scrollAreaWidgetContents_58)
        self.verticalLayout_31.addWidget(self.scrollArea_53)
        self.toolBox_14.addItem(self.detailed_view_accordion_20, "")
        self.visualization_accordion_20 = QtWidgets.QWidget()
        self.visualization_accordion_20.setGeometry(QtCore.QRect(0, 0, 1724, 437))
        self.visualization_accordion_20.setObjectName("visualization_accordion_20")
        self.Visual_Tab_Widget_4 = QtWidgets.QTabWidget(self.visualization_accordion_20)
        self.Visual_Tab_Widget_4.setGeometry(QtCore.QRect(10, 10, 1681, 401))
        self.Visual_Tab_Widget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.Visual_Tab_Widget_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Visual_Tab_Widget_4.setObjectName("Visual_Tab_Widget_4")
        self.tab_137 = QtWidgets.QWidget()

        self.tab_137.setObjectName("tab_137")
        self.Bar_Graph_Area_123 = QtWidgets.QScrollArea(self.tab_137)
        self.Bar_Graph_Area_123.setGeometry(QtCore.QRect(10, 0, 1651, 371))
        self.Bar_Graph_Area_123.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Bar_Graph_Area_123.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Bar_Graph_Area_123.setWidgetResizable(True)
        self.Bar_Graph_Area_123.setObjectName("Bar_Graph_Area_123")
        self.scrollAreaWidgetContents_60 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_60.setGeometry(QtCore.QRect(0, 0, 1641, 369))
        self.scrollAreaWidgetContents_60.setObjectName("scrollAreaWidgetContents_60")
        self.Bar_Graph_Area_123.setWidget(self.scrollAreaWidgetContents_60)

        self.Bar_Graph_Area_123.setWidget(self.add_bar_graph())

        self.Visual_Tab_Widget_4.addTab(self.tab_137, "")
        self.tab_138 = QtWidgets.QWidget()
        self.tab_138.setObjectName("tab_138")
        self.Visual_Tab_Widget_4.addTab(self.tab_138, "")
        self.tab_139 = QtWidgets.QWidget()
        self.tab_139.setObjectName("tab_139")
        self.Visual_Tab_Widget_4.addTab(self.tab_139, "")
        self.toolBox_14.addItem(self.visualization_accordion_20, "")
        self.script_accordion_16 = QtWidgets.QWidget()
        self.script_accordion_16.setGeometry(QtCore.QRect(0, 0, 1724, 437))
        self.script_accordion_16.setObjectName("script_accordion_16")
        self.toolBox_14.addItem(self.script_accordion_16, "")
        self.history_accordion_16 = QtWidgets.QWidget()
        self.history_accordion_16.setGeometry(QtCore.QRect(0, 0, 1724, 437))
        self.history_accordion_16.setObjectName("history_accordion_16")
        self.toolBox_14.addItem(self.history_accordion_16, "")
        self.log_accordion_16 = QtWidgets.QWidget()
        self.log_accordion_16.setGeometry(QtCore.QRect(0, 0, 1724, 437))
        self.log_accordion_16.setObjectName("log_accordion_16")
        self.tableWidget_40 = QtWidgets.QTableWidget(self.log_accordion_16)
        self.tableWidget_40.setGeometry(QtCore.QRect(0, 0, 1761, 441))
        self.tableWidget_40.setObjectName("tableWidget_40")
        self.tableWidget_40.setColumnCount(5)
        self.tableWidget_40.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_40.setItem(4, 4, item)
        self.tableWidget_40.horizontalHeader().setDefaultSectionSize(340)
        self.tableWidget_40.horizontalHeader().setMinimumSectionSize(50)
        self.toolBox_14.addItem(self.log_accordion_16, "")
        self.verticalLayout_2.addWidget(self.toolBox_14)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1792, 24))
        self.menubar.setObjectName("menubar")
        self.menuAVERT = QtWidgets.QMenu(self.menubar)
        self.menuAVERT.setObjectName("menuAVERT")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAVERT.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_32.setCurrentIndex(0)
        self.Visual_Tab_Widget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Tag"))
        self.label_10.setText(_translate("MainWindow", "Search"))
        self.textEdit_2.setHtml(_translate("MainWindow",
                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                           "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.AppleSystemUIFont\'; font-size:13pt;\"><br /></p></body></html>"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "Expression"))
        self.label_6.setText(_translate("MainWindow", "Search Expression"))
        self.label_21.setText(_translate("MainWindow", "Network Packet"))
        self.label.setText(_translate("MainWindow", "Start Date"))
        self.label_20.setText(_translate("MainWindow", "Video"))
        self.label_18.setText(_translate("MainWindow", "All Arifact Types"))
        self.label_26.setText(_translate("MainWindow", "System Call"))
        self.label_13.setText(_translate("MainWindow", "Filters"))
        self.label_2.setText(_translate("MainWindow", "Start Time"))
        self.label_30.setText(_translate("MainWindow", "Value"))
        self.label_28.setText(_translate("MainWindow", "Log"))
        self.label_23.setText(_translate("MainWindow", "Keystroke"))
        self.label_24.setText(_translate("MainWindow", "Mouse Action"))
        self.label_22.setText(_translate("MainWindow", "Process"))
        self.label_11.setText(_translate("MainWindow", "User Profile"))
        self.label_27.setText(_translate("MainWindow", "History"))
        self.label_19.setText(_translate("MainWindow", "Still Screenshot"))
        self.label_12.setText(_translate("MainWindow", "IP Address"))
        self.label_14.setText(_translate("MainWindow", "Value"))
        self.label_25.setText(_translate("MainWindow", "Window History"))
        self.label_29.setText(_translate("MainWindow", "Date and Time"))
        self.label_16.setText(_translate("MainWindow", "Type"))
        self.label_3.setText(_translate("MainWindow", "End Date"))
        self.label_17.setText(_translate("MainWindow", "Value"))
        self.label_15.setText(_translate("MainWindow", "MAC Address"))
        self.label_4.setText(_translate("MainWindow", "End Time"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.label_9.setText(_translate("MainWindow", "AVERT RESULT"))
        item = self.tableWidget_38.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget_38.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget_38.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MAC Address"))
        __sortingEnabled = self.tableWidget_38.isSortingEnabled()
        self.tableWidget_38.setSortingEnabled(False)
        item = self.tableWidget_38.item(0, 0)
        item.setText(_translate("MainWindow", "192.111.222.16"))
        item = self.tableWidget_38.item(0, 1)
        item.setText(_translate("MainWindow", "AA:BB:CCC"))
        self.tableWidget_38.setSortingEnabled(__sortingEnabled)
        self.tabWidget_32.setTabText(self.tabWidget_32.indexOf(self.tab_133), _translate("MainWindow", "User Profile"))
        self.tabWidget_32.setTabText(self.tabWidget_32.indexOf(self.tab_134), _translate("MainWindow", "Description"))
        item = self.tableWidget_39.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Video1"))
        item = self.tableWidget_39.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Timestamp"))
        item = self.tableWidget_39.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget_39.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MAC Address"))
        item = self.tableWidget_39.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        __sortingEnabled = self.tableWidget_39.isSortingEnabled()
        self.tableWidget_39.setSortingEnabled(False)
        item = self.tableWidget_39.item(0, 0)
        item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
        item = self.tableWidget_39.item(0, 1)
        item.setText(_translate("MainWindow", "192.111.222.16"))
        item = self.tableWidget_39.item(0, 2)
        item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
        item = self.tableWidget_39.item(0, 3)
        item.setText(_translate("MainWindow", "Lorem Ipsum"))
        self.tableWidget_39.setSortingEnabled(__sortingEnabled)
        self.pushButton_18.setText(_translate("MainWindow", "Add"))
        self.tabWidget_32.setTabText(self.tabWidget_32.indexOf(self.tab_135), _translate("MainWindow", "Annotation"))
        self.tabWidget_32.setTabText(self.tabWidget_32.indexOf(self.tab_136), _translate("MainWindow", "Tags"))
        self.toolBox_14.setItemText(self.toolBox_14.indexOf(self.detailed_view_accordion_20),
                                    _translate("MainWindow", "Detailed View of Selected Artifact"))
        self.Visual_Tab_Widget_4.setTabText(self.Visual_Tab_Widget_4.indexOf(self.tab_137),
                                            _translate("MainWindow", "Bar Graph"))
        self.Visual_Tab_Widget_4.setTabText(self.Visual_Tab_Widget_4.indexOf(self.tab_138),
                                            _translate("MainWindow", "Time Line"))
        self.Visual_Tab_Widget_4.setTabText(self.Visual_Tab_Widget_4.indexOf(self.tab_139),
                                            _translate("MainWindow", "Pie Chart"))
        self.toolBox_14.setItemText(self.toolBox_14.indexOf(self.visualization_accordion_20),
                                    _translate("MainWindow", "Visualization"))
        self.toolBox_14.setItemText(self.toolBox_14.indexOf(self.script_accordion_16),
                                    _translate("MainWindow", "Script"))
        self.toolBox_14.setItemText(self.toolBox_14.indexOf(self.history_accordion_16),
                                    _translate("MainWindow", "History"))
        self.tableWidget_40.setSortingEnabled(True)
        item = self.tableWidget_40.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_40.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_40.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_40.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_40.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_40.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time Stamp"))
        item = self.tableWidget_40.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Artifact Type"))
        item = self.tableWidget_40.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget_40.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MAC Address"))
        item = self.tableWidget_40.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Action Preformed on Artifact"))
        __sortingEnabled = self.tableWidget_40.isSortingEnabled()
        self.tableWidget_40.setSortingEnabled(False)
        item = self.tableWidget_40.item(0, 0)
        item.setText(_translate("MainWindow", "2020-9-11 06:46:00"))
        item = self.tableWidget_40.item(0, 1)
        item.setText(_translate("MainWindow", "Screenshot"))
        item = self.tableWidget_40.item(0, 2)
        item.setText(_translate("MainWindow", "127.0.0.1"))
        item = self.tableWidget_40.item(0, 3)
        item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
        item = self.tableWidget_40.item(0, 4)
        item.setText(_translate("MainWindow", "Deleted"))
        item = self.tableWidget_40.item(1, 0)
        item.setText(_translate("MainWindow", "2020-9-12 07:46:00"))
        item = self.tableWidget_40.item(1, 1)
        item.setText(_translate("MainWindow", "Video"))
        item = self.tableWidget_40.item(1, 2)
        item.setText(_translate("MainWindow", "127.0.0.1"))
        item = self.tableWidget_40.item(1, 3)
        item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
        item = self.tableWidget_40.item(1, 4)
        item.setText(_translate("MainWindow", "Deleted"))
        item = self.tableWidget_40.item(2, 0)
        item.setText(_translate("MainWindow", "2020-9-13 08:46:00"))
        item = self.tableWidget_40.item(2, 1)
        item.setText(_translate("MainWindow", "Process"))
        item = self.tableWidget_40.item(2, 2)
        item.setText(_translate("MainWindow", "127.0.0.1"))
        item = self.tableWidget_40.item(2, 3)
        item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
        item = self.tableWidget_40.item(2, 4)
        item.setText(_translate("MainWindow", "Captured"))
        item = self.tableWidget_40.item(3, 0)
        item.setText(_translate("MainWindow", "2020-9-14 09:46:00"))
        item = self.tableWidget_40.item(3, 1)
        item.setText(_translate("MainWindow", "System Call"))
        item = self.tableWidget_40.item(3, 2)
        item.setText(_translate("MainWindow", "127.0.0.1"))
        item = self.tableWidget_40.item(3, 3)
        item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
        item = self.tableWidget_40.item(3, 4)
        item.setText(_translate("MainWindow", "Captured"))
        item = self.tableWidget_40.item(4, 0)
        item.setText(_translate("MainWindow", "2020-9-15 10:46:00"))
        item = self.tableWidget_40.item(4, 1)
        item.setText(_translate("MainWindow", "Key Stroke"))
        item = self.tableWidget_40.item(4, 2)
        item.setText(_translate("MainWindow", "127.0.0.1"))
        item = self.tableWidget_40.item(4, 3)
        item.setText(_translate("MainWindow", "H8:F9:A1:7D"))
        item = self.tableWidget_40.item(4, 4)
        item.setText(_translate("MainWindow", "Captured"))
        self.tableWidget_40.setSortingEnabled(__sortingEnabled)
        self.toolBox_14.setItemText(self.toolBox_14.indexOf(self.log_accordion_16),
                                    _translate("MainWindow", "Log Content"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Sync"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Detailed View"))
        self.menuAVERT.setTitle(_translate("MainWindow", "AVERT"))

    def add_sections(self):
        """adds a collapsible sections for every
        (title, widget) tuple in self.sections
        """
        for (title, widget) in self.sections:
            button1 = self.add_button(title)
            section1 = self.add_widget(button1, widget)
            button1.addChild(section1)

    # **& THis is needed
    def add_bar_graph(self):
        set0 = QBarSet('Screenshot')
        set1 = QBarSet('Video')
        set2 = QBarSet('Mouse Action')
        set3 = QBarSet('Window History')

        set0.append([random.randint(0, 10) for i in range(1)])
        set1.append([random.randint(0, 10) for i in range(1)])
        set2.append([random.randint(0, 10) for i in range(1)])
        set3.append([random.randint(0, 10) for i in range(1)])

        series = QBarSeries()
        series.append(set0)
        series.append(set1)
        series.append(set2)
        series.append(set3)

        chart = QChart()
        chart.addSeries(series)
        chart.setTitle('Bar Chart')
        chart.setAnimationOptions(QChart.SeriesAnimations)

        axisX = QBarCategoryAxis()
        axisX.append('Components')

        axisY = QValueAxis()
        axisY.setRange(0, 100)
        chart.addAxis(axisX, Qt.AlignBottom)
        chart.addAxis(axisY, Qt.AlignLeft)

        chart.legend().setVisible(True)
        chart.legend().setAlignment(Qt.AlignBottom)

        chart_view = QChartView(chart)

        return chart_view

    def define_sections(self):
        """reimplement this to define all your sections
        and add them as (title, widget) tuples to self.sections
        """
        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        layout.addWidget(QtWidgets.QCalendarWidget())
        title = "Selected Artifacts"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        self.checkBox_Visualization = QtWidgets.QCheckBox()
        self.checkBox_Visualization.setObjectName("checkBox_Visualization")
        layout.addWidget(self.checkBox_Visualization)

        title = "Visualization"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        # self.tab_2 = QtWidgets.QWidget(widget)
        # self.tab_2.setObjectName("tab_2")
        layout = QVBoxLayout(widget)

        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox = QtWidgets.QCheckBox()
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(QtWidgets.QCheckBox())
        self.verticalLayout_6.addWidget(QtWidgets.QCheckBox())
        self.verticalLayout_6.addWidget(QtWidgets.QCheckBox())
        self.verticalLayout_6.addWidget(self.checkBox)
        layout.addLayout(self.verticalLayout_6)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_31 = QtWidgets.QLabel()
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 6, 1, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit()
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.textEdit_3.sizePolicy().hasHeightForWidth())
        # self.textEdit_3.setSizePolicy(sizePolicy)
        self.textEdit_3.setMaximumSize(QtCore.QSize(400, 25))
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_4.addWidget(self.textEdit_3, 2, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton()
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 6, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel()
        self.label_32.setStyleSheet("")
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel()
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_33 = QtWidgets.QLabel()
        self.verticalLayout_6.addLayout(self.gridLayout_4)

        title = "Script"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        layout.addWidget(QtWidgets.QCheckBox())
        title = "History"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        layout.addWidget(QtWidgets.QCheckBox())
        title = "Log Content"
        self.sections.append((title, widget))
        # self.gridLayout_2.addWidget(widget, 7, 2, 1, 1)

    def add_button(self, title):
        """creates a QTreeWidgetItem containing a button
        to expand or collapse its section
        """
        item = QTreeWidgetItem()
        self.tree.addTopLevelItem(item)
        self.tree.setItemWidget(item, 0, SectionExpandButton(item, text=title))
        return item

    def add_widget(self, button, widget):
        """creates a QWidgetItem containing the widget,
        as child of the button-QWidgetItem
        """
        section = QTreeWidgetItem(button)
        section.setDisabled(True)
        self.tree.setItemWidget(section, 0, widget)
        return section


class SectionExpandButton(QPushButton):
    """a QPushbutton that can expand or collapse its section
    """

    def __init__(self, item, text="", parent=None):
        super().__init__(text, parent)
        self.section = item
        self.clicked.connect(self.on_clicked)

    def on_clicked(self):
        """toggle expand/collapse of section by clicking
        """
        if self.section.isExpanded():
            self.section.setExpanded(False)
        else:
            self.section.setExpanded(True)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    app.exec()