import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QPushButton, QDialog, QTreeWidget, QTreeWidgetItem, QVBoxLayout,
                             QHBoxLayout, QFrame, QLabel, QApplication, QMainWindow)
# from PyQt6 import QtCore, QtGui, QtWidgets
# from PyQt6.QtWidgets import (QPushButton, QDialog, QTreeWidget, QTreeWidgetItem, QVBoxLayout,
                            #  QHBoxLayout, QFrame, QLabel,
                            #  QApplication, QApplication, QMainWindow, QPushButton)
import detaileddescription

import avertUI_implement_tab3


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.tree = QTreeWidget()
        self.tree.setHeaderHidden(True)
        self.sections = []
        self.define_sections()
        self.add_sections()
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1792, 1120)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1766, 1385))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.tab_1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_1)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMaximumSize(QtCore.QSize(400, 25))
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_2.addWidget(self.textEdit_2, 2, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.tab_1)
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 6, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 19, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_1)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 12, 0, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_23.setText("")
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_3.addWidget(self.checkBox_23, 13, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_1)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 15, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_1)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_3.addWidget(self.dateEdit_2, 19, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 20, 0, 1, 1)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.tab_1)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout_3.addWidget(self.timeEdit_2, 20, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_1)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_1)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 6, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_1)
        self.label_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_1)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 8, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_1)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 0, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.tab_1)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_3.addWidget(self.timeEdit, 18, 1, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_3.addWidget(self.checkBox_20, 15, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_1)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 10, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.tab_1)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_3.addWidget(self.dateEdit, 17, 1, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_3.addWidget(self.checkBox_21, 8, 1, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_3.addWidget(self.checkBox_18, 10, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_1)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_29.setStyleSheet("")
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 16, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_1)
        self.label_30.setStyleSheet("")
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 16, 1, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_3.addWidget(self.checkBox_19, 11, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_24.setText("")
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_3.addWidget(self.checkBox_24, 14, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_1)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 14, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_1)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_3.addWidget(self.checkBox_17, 9, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_1)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 4, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_1)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_1)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 13, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_3.addWidget(self.checkBox_16, 7, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_4.setMaximumSize(QtCore.QSize(150, 20))
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_3.addWidget(self.comboBox_4, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 18, 0, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_22.setText("")
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_3.addWidget(self.checkBox_22, 12, 1, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_3.addWidget(self.checkBox_14, 5, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_1)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 11, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_1)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_1)
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_1)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 9, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_3.setMaximumSize(QtCore.QSize(150, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 3, 1, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_3.addWidget(self.checkBox_15, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 17, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        self.label_8.setMaximumSize(QtCore.QSize(20, 20))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_2.setMaximumSize(QtCore.QSize(150, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.tab_1)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 7, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.toolBox_12 = QtWidgets.QToolBox(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_12.sizePolicy().hasHeightForWidth())
        self.toolBox_12.setSizePolicy(sizePolicy)
        self.toolBox_12.setMinimumSize(QtCore.QSize(0, 600))
        self.toolBox_12.setObjectName("toolBox_12")
        self.detailed_view_accordion_14 = QtWidgets.QWidget()
        self.detailed_view_accordion_14.setGeometry(QtCore.QRect(0, 0, 1696, 432))
        self.detailed_view_accordion_14.setObjectName("detailed_view_accordion_14")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.detailed_view_accordion_14)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.scrollArea_41 = QtWidgets.QScrollArea(self.detailed_view_accordion_14)
        self.scrollArea_41.setWidgetResizable(True)
        self.scrollArea_41.setObjectName("scrollArea_41")
        self.scrollAreaWidgetContents_43 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_43.setGeometry(QtCore.QRect(0, 0, 1670, 406))
        self.scrollAreaWidgetContents_43.setObjectName("scrollAreaWidgetContents_43")
        self.tabWidget_26 = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_43)
        self.tabWidget_26.setGeometry(QtCore.QRect(10, 0, 1681, 401))
        self.tabWidget_26.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_26.setObjectName("tabWidget_26")

        # Detailed View of Selected Artifact > User Profile
        self.tab_100 = QtWidgets.QWidget()
        self.tab_100.setObjectName("tab_100")
        self.scrollArea_42 = QtWidgets.QScrollArea(self.tab_100)
        self.scrollArea_42.setGeometry(QtCore.QRect(10, 0, 1651, 371))
        self.scrollArea_42.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_42.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_42.setWidgetResizable(True)
        self.scrollArea_42.setObjectName("scrollArea_42")
        self.scrollAreaWidgetContents_44 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_44.setGeometry(QtCore.QRect(0, 0, 1633, 369))
        self.scrollAreaWidgetContents_44.setObjectName("scrollAreaWidgetContents_44")
        self.tableWidget_23 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_44)
        self.tableWidget_23.setGeometry(QtCore.QRect(20, 10, 1591, 351))
        self.tableWidget_23.setObjectName("tableWidget_23")
        self.tableWidget_23.setColumnCount(2)
        self.tableWidget_23.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_23.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_23.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_23.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_23.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_23.setItem(0, 1, item)
        self.tableWidget_23.horizontalHeader().setDefaultSectionSize(400)
        self.scrollArea_42.setWidget(self.scrollAreaWidgetContents_44)
        self.tabWidget_26.addTab(self.tab_100, "")

        # Detailed View of Seelected Artifact > Description START
        self.description_tab = QtWidgets.QTabWidget(self.tabWidget_26)
        self.description_tab.setGeometry(QtCore.QRect(9, 9, 1581, 341))
        self.description_tab.setObjectName("description_tab")
        self.descriptionvideo_tab = QtWidgets.QWidget()
        self.descriptionvideo_tab.setObjectName("descriptionvideo_tab")
        self.descriptionvideo_frame = QtWidgets.QFrame(self.descriptionvideo_tab)
        self.descriptionvideo_frame.setGeometry(QtCore.QRect(80, 20, 391, 291))
        self.descriptionvideo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descriptionvideo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.descriptionvideo_frame.setObjectName("descriptionvideo_frame")
        self.label_88 = QtWidgets.QLabel(self.descriptionvideo_frame)
        self.label_88.setGeometry(QtCore.QRect(10, 0, 391, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.label_88.sizePolicy().hasHeightForWidth())
        self.label_88.setSizePolicy(sizePolicy)
        self.label_88.setObjectName("label_88")
        self.descriptionvideo_timestamp_label = QtWidgets.QLabel(self.descriptionvideo_tab)
        self.descriptionvideo_timestamp_label.setGeometry(QtCore.QRect(770, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label.setFont(font)
        self.descriptionvideo_timestamp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label.setObjectName("descriptionvideo_timestamp_label")
        self.label_41 = QtWidgets.QLabel(self.descriptionvideo_tab)
        self.label_41.setGeometry(QtCore.QRect(950, 50, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.descriptionvideo_timestamp_label_2 = QtWidgets.QLabel(self.descriptionvideo_tab)
        self.descriptionvideo_timestamp_label_2.setGeometry(QtCore.QRect(770, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_2.setFont(font)
        self.descriptionvideo_timestamp_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_2.setObjectName("descriptionvideo_timestamp_label_2")
        self.label_42 = QtWidgets.QLabel(self.descriptionvideo_tab)
        self.label_42.setGeometry(QtCore.QRect(950, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.descriptionvideo_timestamp_label_3 = QtWidgets.QLabel(self.descriptionvideo_tab)
        self.descriptionvideo_timestamp_label_3.setGeometry(QtCore.QRect(770, 150, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_3.setFont(font)
        self.descriptionvideo_timestamp_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_3.setObjectName("descriptionvideo_timestamp_label_3")
        self.label_43 = QtWidgets.QLabel(self.descriptionvideo_tab)
        self.label_43.setGeometry(QtCore.QRect(950, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.descriptionvideo_timestamp_label_4 = QtWidgets.QLabel(self.descriptionvideo_tab)
        self.descriptionvideo_timestamp_label_4.setGeometry(QtCore.QRect(770, 200, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_4.setFont(font)
        self.descriptionvideo_timestamp_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_4.setObjectName("descriptionvideo_timestamp_label_4")
        self.label_44 = QtWidgets.QLabel(self.descriptionvideo_tab)
        self.label_44.setGeometry(QtCore.QRect(950, 200, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.description_tab.addTab(self.descriptionvideo_tab, "")
        self.descriptionstillscreenshot_tab = QtWidgets.QWidget()
        self.descriptionstillscreenshot_tab.setObjectName("descriptionstillscreenshot_tab")
        self.descriptionvideo_timestamp_label_5 = QtWidgets.QLabel(self.descriptionstillscreenshot_tab)
        self.descriptionvideo_timestamp_label_5.setGeometry(QtCore.QRect(800, 190, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_5.setFont(font)
        self.descriptionvideo_timestamp_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_5.setObjectName("descriptionvideo_timestamp_label_5")
        self.descriptionvideo_timestamp_label_6 = QtWidgets.QLabel(self.descriptionstillscreenshot_tab)
        self.descriptionvideo_timestamp_label_6.setGeometry(QtCore.QRect(800, 140, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_6.setFont(font)
        self.descriptionvideo_timestamp_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_6.setObjectName("descriptionvideo_timestamp_label_6")
        self.label_45 = QtWidgets.QLabel(self.descriptionstillscreenshot_tab)
        self.label_45.setGeometry(QtCore.QRect(1030, 190, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.descriptionvideo_frame_2 = QtWidgets.QFrame(self.descriptionstillscreenshot_tab)
        self.descriptionvideo_frame_2.setGeometry(QtCore.QRect(9, 10, 491, 291))
        self.descriptionvideo_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descriptionvideo_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.descriptionvideo_frame_2.setObjectName("descriptionvideo_frame_2")
        self.label_89 = QtWidgets.QLabel(self.descriptionvideo_frame_2)
        self.label_89.setGeometry(QtCore.QRect(0, 0, 511, 301))
        self.label_89.setObjectName("label_89")
        self.label_46 = QtWidgets.QLabel(self.descriptionstillscreenshot_tab)
        self.label_46.setGeometry(QtCore.QRect(1030, 140, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.descriptionvideo_timestamp_label_7 = QtWidgets.QLabel(self.descriptionstillscreenshot_tab)
        self.descriptionvideo_timestamp_label_7.setGeometry(QtCore.QRect(800, 90, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_7.setFont(font)
        self.descriptionvideo_timestamp_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_7.setObjectName("descriptionvideo_timestamp_label_7")
        self.label_47 = QtWidgets.QLabel(self.descriptionstillscreenshot_tab)
        self.label_47.setGeometry(QtCore.QRect(1030, 90, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.description_tab.addTab(self.descriptionstillscreenshot_tab, "")
        self.descriptionsystemcall_tab = QtWidgets.QWidget()
        self.descriptionsystemcall_tab.setObjectName("descriptionsystemcall_tab")
        self.descriptionvideo_timestamp_label_8 = QtWidgets.QLabel(self.descriptionsystemcall_tab)
        self.descriptionvideo_timestamp_label_8.setGeometry(QtCore.QRect(550, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_8.setFont(font)
        self.descriptionvideo_timestamp_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_8.setObjectName("descriptionvideo_timestamp_label_8")
        self.label_48 = QtWidgets.QLabel(self.descriptionsystemcall_tab)
        self.label_48.setGeometry(QtCore.QRect(800, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.descriptionvideo_timestamp_label_9 = QtWidgets.QLabel(self.descriptionsystemcall_tab)
        self.descriptionvideo_timestamp_label_9.setGeometry(QtCore.QRect(550, 150, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_9.setFont(font)
        self.descriptionvideo_timestamp_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_9.setObjectName("descriptionvideo_timestamp_label_9")
        self.descriptionvideo_timestamp_label_10 = QtWidgets.QLabel(self.descriptionsystemcall_tab)
        self.descriptionvideo_timestamp_label_10.setGeometry(QtCore.QRect(550, 100, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_10.setFont(font)
        self.descriptionvideo_timestamp_label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_10.setObjectName("descriptionvideo_timestamp_label_10")
        self.label_49 = QtWidgets.QLabel(self.descriptionsystemcall_tab)
        self.label_49.setGeometry(QtCore.QRect(800, 50, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.descriptionsystemcall_tab)
        self.label_50.setGeometry(QtCore.QRect(800, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.descriptionvideo_timestamp_label_11 = QtWidgets.QLabel(self.descriptionsystemcall_tab)
        self.descriptionvideo_timestamp_label_11.setGeometry(QtCore.QRect(550, 200, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_11.setFont(font)
        self.descriptionvideo_timestamp_label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_11.setObjectName("descriptionvideo_timestamp_label_11")
        self.descriptionvideo_timestamp_label_13 = QtWidgets.QLabel(self.descriptionsystemcall_tab)
        self.descriptionvideo_timestamp_label_13.setGeometry(QtCore.QRect(550, 250, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_13.setFont(font)
        self.descriptionvideo_timestamp_label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_13.setObjectName("descriptionvideo_timestamp_label_13")
        self.label_52 = QtWidgets.QLabel(self.descriptionsystemcall_tab)
        self.label_52.setGeometry(QtCore.QRect(800, 200, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.descriptionsystemcall_tab)
        self.label_53.setGeometry(QtCore.QRect(800, 250, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.description_tab.addTab(self.descriptionsystemcall_tab, "")
        self.descriptionprocess_tab = QtWidgets.QWidget()
        self.descriptionprocess_tab.setObjectName("descriptionprocess_tab")
        self.label_51 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_51.setGeometry(QtCore.QRect(310, 80, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.label_54 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_54.setGeometry(QtCore.QRect(310, 230, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_55.setGeometry(QtCore.QRect(310, 30, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.descriptionvideo_timestamp_label_12 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_12.setGeometry(QtCore.QRect(80, 180, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_12.setFont(font)
        self.descriptionvideo_timestamp_label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_12.setObjectName("descriptionvideo_timestamp_label_12")
        self.label_56 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_56.setGeometry(QtCore.QRect(310, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_56.setFont(font)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.descriptionvideo_timestamp_label_14 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_14.setGeometry(QtCore.QRect(80, 230, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_14.setFont(font)
        self.descriptionvideo_timestamp_label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_14.setObjectName("descriptionvideo_timestamp_label_14")
        self.descriptionvideo_timestamp_label_15 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_15.setGeometry(QtCore.QRect(80, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_15.setFont(font)
        self.descriptionvideo_timestamp_label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_15.setObjectName("descriptionvideo_timestamp_label_15")
        self.label_57 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_57.setGeometry(QtCore.QRect(310, 180, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.descriptionvideo_timestamp_label_16 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_16.setGeometry(QtCore.QRect(80, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_16.setFont(font)
        self.descriptionvideo_timestamp_label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_16.setObjectName("descriptionvideo_timestamp_label_16")
        self.descriptionvideo_timestamp_label_17 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_17.setGeometry(QtCore.QRect(80, 130, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_17.setFont(font)
        self.descriptionvideo_timestamp_label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_17.setObjectName("descriptionvideo_timestamp_label_17")
        self.label_58 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_58.setGeometry(QtCore.QRect(810, 80, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_59.setGeometry(QtCore.QRect(810, 230, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_59.setFont(font)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_60.setGeometry(QtCore.QRect(810, 30, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_60.setFont(font)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.descriptionvideo_timestamp_label_18 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_18.setGeometry(QtCore.QRect(580, 180, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_18.setFont(font)
        self.descriptionvideo_timestamp_label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_18.setObjectName("descriptionvideo_timestamp_label_18")
        self.label_61 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_61.setGeometry(QtCore.QRect(810, 130, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.descriptionvideo_timestamp_label_19 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_19.setGeometry(QtCore.QRect(580, 230, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_19.setFont(font)
        self.descriptionvideo_timestamp_label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_19.setObjectName("descriptionvideo_timestamp_label_19")
        self.descriptionvideo_timestamp_label_20 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_20.setGeometry(QtCore.QRect(580, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_20.setFont(font)
        self.descriptionvideo_timestamp_label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_20.setObjectName("descriptionvideo_timestamp_label_20")
        self.label_62 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_62.setGeometry(QtCore.QRect(810, 180, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.descriptionvideo_timestamp_label_21 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_21.setGeometry(QtCore.QRect(580, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_21.setFont(font)
        self.descriptionvideo_timestamp_label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_21.setObjectName("descriptionvideo_timestamp_label_21")
        self.descriptionvideo_timestamp_label_22 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_22.setGeometry(QtCore.QRect(580, 130, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_22.setFont(font)
        self.descriptionvideo_timestamp_label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_22.setObjectName("descriptionvideo_timestamp_label_22")
        self.label_63 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_63.setGeometry(QtCore.QRect(1350, 30, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_64.setGeometry(QtCore.QRect(1350, 80, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.descriptionvideo_timestamp_label_23 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_23.setGeometry(QtCore.QRect(1120, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_23.setFont(font)
        self.descriptionvideo_timestamp_label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_23.setObjectName("descriptionvideo_timestamp_label_23")
        self.descriptionvideo_timestamp_label_24 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_24.setGeometry(QtCore.QRect(1120, 180, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_24.setFont(font)
        self.descriptionvideo_timestamp_label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_24.setObjectName("descriptionvideo_timestamp_label_24")
        self.label_65 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_65.setGeometry(QtCore.QRect(1350, 180, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_65.setFont(font)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_66.setGeometry(QtCore.QRect(1350, 130, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_66.setFont(font)
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.descriptionvideo_timestamp_label_25 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_25.setGeometry(QtCore.QRect(1120, 230, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_25.setFont(font)
        self.descriptionvideo_timestamp_label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_25.setObjectName("descriptionvideo_timestamp_label_25")
        self.descriptionvideo_timestamp_label_26 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_26.setGeometry(QtCore.QRect(1120, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_26.setFont(font)
        self.descriptionvideo_timestamp_label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_26.setObjectName("descriptionvideo_timestamp_label_26")
        self.label_67 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.label_67.setGeometry(QtCore.QRect(1350, 230, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_67.setFont(font)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.descriptionvideo_timestamp_label_27 = QtWidgets.QLabel(self.descriptionprocess_tab)
        self.descriptionvideo_timestamp_label_27.setGeometry(QtCore.QRect(1120, 130, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_27.setFont(font)
        self.descriptionvideo_timestamp_label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_27.setObjectName("descriptionvideo_timestamp_label_27")
        self.description_tab.addTab(self.descriptionprocess_tab, "")
        self.descriptionwindowhistory_tab = QtWidgets.QWidget()
        self.descriptionwindowhistory_tab.setObjectName("descriptionwindowhistory_tab")
        self.label_68 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_68.setGeometry(QtCore.QRect(800, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_68.setFont(font)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_69.setGeometry(QtCore.QRect(1310, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_69.setFont(font)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_70.setGeometry(QtCore.QRect(800, 160, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_70.setFont(font)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.descriptionvideo_timestamp_label_29 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_29.setGeometry(QtCore.QRect(530, 210, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_29.setFont(font)
        self.descriptionvideo_timestamp_label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_29.setObjectName("descriptionvideo_timestamp_label_29")
        self.descriptionvideo_timestamp_label_30 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_30.setGeometry(QtCore.QRect(30, 210, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_30.setFont(font)
        self.descriptionvideo_timestamp_label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_30.setObjectName("descriptionvideo_timestamp_label_30")
        self.descriptionvideo_timestamp_label_31 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_31.setGeometry(QtCore.QRect(1070, 110, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_31.setFont(font)
        self.descriptionvideo_timestamp_label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_31.setObjectName("descriptionvideo_timestamp_label_31")
        self.label_71 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_71.setGeometry(QtCore.QRect(260, 210, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_71.setFont(font)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.descriptionvideo_timestamp_label_32 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_32.setGeometry(QtCore.QRect(1070, 160, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_32.setFont(font)
        self.descriptionvideo_timestamp_label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_32.setObjectName("descriptionvideo_timestamp_label_32")
        self.descriptionvideo_timestamp_label_33 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_33.setGeometry(QtCore.QRect(530, 160, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_33.setFont(font)
        self.descriptionvideo_timestamp_label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_33.setObjectName("descriptionvideo_timestamp_label_33")
        self.label_72 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_72.setGeometry(QtCore.QRect(1310, 160, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_72.setFont(font)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.descriptionvideo_timestamp_label_34 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_34.setGeometry(QtCore.QRect(30, 110, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_34.setFont(font)
        self.descriptionvideo_timestamp_label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_34.setObjectName("descriptionvideo_timestamp_label_34")
        self.label_74 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_74.setGeometry(QtCore.QRect(1310, 110, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_74.setFont(font)
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.descriptionvideo_timestamp_label_35 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_35.setGeometry(QtCore.QRect(1070, 210, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_35.setFont(font)
        self.descriptionvideo_timestamp_label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_35.setObjectName("descriptionvideo_timestamp_label_35")
        self.descriptionvideo_timestamp_label_36 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_36.setGeometry(QtCore.QRect(530, 110, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_36.setFont(font)
        self.descriptionvideo_timestamp_label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_36.setObjectName("descriptionvideo_timestamp_label_36")
        self.label_75 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_75.setGeometry(QtCore.QRect(260, 160, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_75.setFont(font)
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_76.setGeometry(QtCore.QRect(1310, 210, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_76.setFont(font)
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_77.setGeometry(QtCore.QRect(260, 110, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_77.setFont(font)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_78.setGeometry(QtCore.QRect(260, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_78.setFont(font)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.descriptionvideo_timestamp_label_38 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_38.setGeometry(QtCore.QRect(30, 60, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_38.setFont(font)
        self.descriptionvideo_timestamp_label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_38.setObjectName("descriptionvideo_timestamp_label_38")
        self.descriptionvideo_timestamp_label_39 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_39.setGeometry(QtCore.QRect(1070, 60, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_39.setFont(font)
        self.descriptionvideo_timestamp_label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_39.setObjectName("descriptionvideo_timestamp_label_39")
        self.descriptionvideo_timestamp_label_40 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_40.setGeometry(QtCore.QRect(30, 160, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_40.setFont(font)
        self.descriptionvideo_timestamp_label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_40.setObjectName("descriptionvideo_timestamp_label_40")
        self.label_81 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_81.setGeometry(QtCore.QRect(800, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_81.setFont(font)
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.descriptionvideo_timestamp_label_42 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.descriptionvideo_timestamp_label_42.setGeometry(QtCore.QRect(530, 60, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_42.setFont(font)
        self.descriptionvideo_timestamp_label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_42.setObjectName("descriptionvideo_timestamp_label_42")
        self.label_82 = QtWidgets.QLabel(self.descriptionwindowhistory_tab)
        self.label_82.setGeometry(QtCore.QRect(800, 210, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_82.setFont(font)
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.description_tab.addTab(self.descriptionwindowhistory_tab, "")
        self.descriptionnetwork_tab = QtWidgets.QWidget()
        self.descriptionnetwork_tab.setObjectName("descriptionnetwork_tab")
        self.description_tab.addTab(self.descriptionnetwork_tab, "")
        self.descriptionmouse_tab = QtWidgets.QWidget()
        self.descriptionmouse_tab.setObjectName("descriptionmouse_tab")
        self.label_73 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.label_73.setGeometry(QtCore.QRect(810, 60, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_73.setFont(font)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.label_79 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.label_79.setGeometry(QtCore.QRect(810, 210, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_79.setFont(font)
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.label_80.setGeometry(QtCore.QRect(810, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_80.setFont(font)
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.descriptionvideo_timestamp_label_28 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.descriptionvideo_timestamp_label_28.setGeometry(QtCore.QRect(560, 160, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_28.setFont(font)
        self.descriptionvideo_timestamp_label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_28.setObjectName("descriptionvideo_timestamp_label_28")
        self.label_83 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.label_83.setGeometry(QtCore.QRect(810, 110, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_83.setFont(font)
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.descriptionvideo_timestamp_label_37 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.descriptionvideo_timestamp_label_37.setGeometry(QtCore.QRect(560, 210, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_37.setFont(font)
        self.descriptionvideo_timestamp_label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_37.setObjectName("descriptionvideo_timestamp_label_37")
        self.descriptionvideo_timestamp_label_41 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.descriptionvideo_timestamp_label_41.setGeometry(QtCore.QRect(560, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_41.setFont(font)
        self.descriptionvideo_timestamp_label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_41.setObjectName("descriptionvideo_timestamp_label_41")
        self.label_84 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.label_84.setGeometry(QtCore.QRect(810, 160, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_84.setFont(font)
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.descriptionvideo_timestamp_label_43 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.descriptionvideo_timestamp_label_43.setGeometry(QtCore.QRect(560, 60, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_43.setFont(font)
        self.descriptionvideo_timestamp_label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_43.setObjectName("descriptionvideo_timestamp_label_43")
        self.descriptionvideo_timestamp_label_44 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.descriptionvideo_timestamp_label_44.setGeometry(QtCore.QRect(560, 110, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_44.setFont(font)
        self.descriptionvideo_timestamp_label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_44.setObjectName("descriptionvideo_timestamp_label_44")
        self.descriptionvideo_timestamp_label_45 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.descriptionvideo_timestamp_label_45.setGeometry(QtCore.QRect(560, 260, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_45.setFont(font)
        self.descriptionvideo_timestamp_label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_45.setObjectName("descriptionvideo_timestamp_label_45")
        self.label_85 = QtWidgets.QLabel(self.descriptionmouse_tab)
        self.label_85.setGeometry(QtCore.QRect(810, 260, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_85.setFont(font)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.description_tab.addTab(self.descriptionmouse_tab, "")
        self.descriptionkeystroke_tab = QtWidgets.QWidget()
        self.descriptionkeystroke_tab.setObjectName("descriptionkeystroke_tab")
        self.descriptionvideo_timestamp_label_46 = QtWidgets.QLabel(self.descriptionkeystroke_tab)
        self.descriptionvideo_timestamp_label_46.setGeometry(QtCore.QRect(550, 150, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_46.setFont(font)
        self.descriptionvideo_timestamp_label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_46.setObjectName("descriptionvideo_timestamp_label_46")
        self.descriptionvideo_timestamp_label_47 = QtWidgets.QLabel(self.descriptionkeystroke_tab)
        self.descriptionvideo_timestamp_label_47.setGeometry(QtCore.QRect(550, 100, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.descriptionvideo_timestamp_label_47.setFont(font)
        self.descriptionvideo_timestamp_label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionvideo_timestamp_label_47.setObjectName("descriptionvideo_timestamp_label_47")
        self.label_86 = QtWidgets.QLabel(self.descriptionkeystroke_tab)
        self.label_86.setGeometry(QtCore.QRect(800, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_86.setFont(font)
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.descriptionkeystroke_tab)
        self.label_87.setGeometry(QtCore.QRect(800, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_87.setFont(font)
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.description_tab.addTab(self.descriptionkeystroke_tab, "")
        # Detailed View of Seelected Artifact > Description END

        self.tabWidget_26.addTab(self.description_tab, "")
        self.tab_102 = QtWidgets.QWidget()
        self.tab_102.setObjectName("tab_102")
        self.tableWidget_24 = QtWidgets.QTableWidget(self.tab_102)
        self.tableWidget_24.setGeometry(QtCore.QRect(10, 10, 1651, 361))
        self.tableWidget_24.setObjectName("tableWidget_24")
        self.tableWidget_24.setColumnCount(4)
        self.tableWidget_24.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_24.setItem(0, 3, item)
        self.tableWidget_24.horizontalHeader().setDefaultSectionSize(350)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_102)
        self.pushButton_12.setGeometry(QtCore.QRect(900, 110, 113, 32))
        self.pushButton_12.setObjectName("pushButton_12")
        self.textEdit_14 = QtWidgets.QTextEdit(self.tab_102)
        self.textEdit_14.setGeometry(QtCore.QRect(420, 70, 431, 79))
        self.textEdit_14.setObjectName("textEdit_14")
        self.tabWidget_26.addTab(self.tab_102, "")
        self.tab_103 = QtWidgets.QWidget()
        self.tab_103.setObjectName("tab_103")
        self.tabWidget_26.addTab(self.tab_103, "")
        self.scrollArea_41.setWidget(self.scrollAreaWidgetContents_43)
        self.verticalLayout_25.addWidget(self.scrollArea_41)
        self.toolBox_12.addItem(self.detailed_view_accordion_14, "")
        self.visualization_accordion_14 = QtWidgets.QWidget()
        self.visualization_accordion_14.setGeometry(QtCore.QRect(0, 0, 1696, 432))
        self.visualization_accordion_14.setObjectName("visualization_accordion_14")
        self.toolBox_12.addItem(self.visualization_accordion_14, "")
        self.script_accordion_10 = QtWidgets.QWidget()
        self.script_accordion_10.setGeometry(QtCore.QRect(0, 0, 1696, 432))
        self.script_accordion_10.setObjectName("script_accordion_10")
        self.toolBox_12.addItem(self.script_accordion_10, "")
        self.history_accordion_10 = QtWidgets.QWidget()
        self.history_accordion_10.setGeometry(QtCore.QRect(0, 0, 1696, 432))
        self.history_accordion_10.setObjectName("history_accordion_10")
        self.toolBox_12.addItem(self.history_accordion_10, "")
        self.log_accordion_10 = QtWidgets.QWidget()
        self.log_accordion_10.setGeometry(QtCore.QRect(0, 0, 1696, 432))
        self.log_accordion_10.setObjectName("log_accordion_10")
        self.toolBox_12.addItem(self.log_accordion_10, "")
        self.verticalLayout_3.addWidget(self.toolBox_12)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget.addTab(self.tab_2, "")

        self.tab_3 = avertUI_implement_tab3.getAllFrameForTab3()
        
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1792, 22))
        self.menubar.setObjectName("menubar")
        self.menuAVERT = QtWidgets.QMenu(self.menubar)
        self.menuAVERT.setObjectName("menuAVERT")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAVERT.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_26.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "AVERT RESULT"))
        self.label_6.setText(_translate("MainWindow", "Search Expression"))
        self.label_10.setText(_translate("MainWindow", "Search"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "Expression"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.label_3.setText(_translate("MainWindow", "End Date"))
        self.label_25.setText(_translate("MainWindow", "Window History"))
        self.label_28.setText(_translate("MainWindow", "Log"))
        self.label_4.setText(_translate("MainWindow", "End Time"))
        self.label_13.setText(_translate("MainWindow", "Filters"))
        self.label_19.setText(_translate("MainWindow", "Still Screenshot"))
        self.label_15.setText(_translate("MainWindow", "MAC Address"))
        self.label_21.setText(_translate("MainWindow", "Network Packet"))
        self.label_16.setText(_translate("MainWindow", "Type"))
        self.label_23.setText(_translate("MainWindow", "Keystroke"))
        self.label_29.setText(_translate("MainWindow", "Date and Time"))
        self.label_30.setText(_translate("MainWindow", "Value"))
        self.label_11.setText(_translate("MainWindow", "User Profile"))
        self.label_27.setText(_translate("MainWindow", "History"))
        self.label_18.setText(_translate("MainWindow", "All Arifact Types"))
        self.label_17.setText(_translate("MainWindow", "Value"))
        self.label_14.setText(_translate("MainWindow", "Value"))
        self.label_26.setText(_translate("MainWindow", "System Call"))
        self.label_2.setText(_translate("MainWindow", "Start Time"))
        self.label_24.setText(_translate("MainWindow", "Mouse Action"))
        self.label_20.setText(_translate("MainWindow", "Video"))
        self.label_12.setText(_translate("MainWindow", "IP Address"))
        self.label_22.setText(_translate("MainWindow", "Process"))
        self.label.setText(_translate("MainWindow", "Start Date"))
        self.label_8.setText(_translate("MainWindow", "Tag"))
        item = self.tableWidget_23.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget_23.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget_23.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MAC Address"))
        __sortingEnabled = self.tableWidget_23.isSortingEnabled()
        self.tableWidget_23.setSortingEnabled(False)
        item = self.tableWidget_23.item(0, 0)
        item.setText(_translate("MainWindow", "192.111.222.16"))
        item = self.tableWidget_23.item(0, 1)
        item.setText(_translate("MainWindow", "AA:BB:CCC"))
        self.tableWidget_23.setSortingEnabled(__sortingEnabled)
        self.tabWidget_26.setTabText(self.tabWidget_26.indexOf(self.tab_100), _translate("MainWindow", "User Profile"))
        self.tabWidget_26.setTabText(self.tabWidget_26.indexOf(self.description_tab), _translate("MainWindow", "Description"))

        self.description_tab.setCurrentIndex(1)

        #DESCRIPTION DETAILED VIEW START
        self.label_88.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/detaileddescription/Screen Shot 2021-09-12 at 11.29.07 AM.png\"/></p></body></html>"))
        self.descriptionvideo_timestamp_label.setText(_translate("MainWindow", "Timestamp:"))
        self.label_41.setText(_translate("MainWindow", "10-6-26 02:31:29"))
        self.descriptionvideo_timestamp_label_2.setText(_translate("MainWindow", "Video Size:"))
        self.label_42.setText(_translate("MainWindow", "60MB"))
        self.descriptionvideo_timestamp_label_3.setText(_translate("MainWindow", "Video Resolution:"))
        self.label_43.setText(_translate("MainWindow", "1260 x 680"))
        self.descriptionvideo_timestamp_label_4.setText(_translate("MainWindow", "Video Frame Rate:"))
        self.label_44.setText(_translate("MainWindow", "24fps"))
        self.description_tab.setTabText(self.description_tab.indexOf(self.descriptionvideo_tab), _translate("MainWindow", "Video"))
        self.descriptionvideo_timestamp_label_5.setText(_translate("MainWindow", "Still Screenshot Format:"))
        self.descriptionvideo_timestamp_label_6.setText(_translate("MainWindow", "Still Screenshot Size:"))
        self.label_45.setText(_translate("MainWindow", "????????"))
        self.label_89.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/detaileddescription/Blank diagram - Page 2 copy.jpg\"/></p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "60MB"))
        self.descriptionvideo_timestamp_label_7.setText(_translate("MainWindow", "Timestamp:"))
        self.label_47.setText(_translate("MainWindow", "10-6-26 02:31:29"))
        self.description_tab.setTabText(self.description_tab.indexOf(self.descriptionstillscreenshot_tab), _translate("MainWindow", "Still Screenshot"))
        self.descriptionvideo_timestamp_label_8.setText(_translate("MainWindow", "Timestamp:"))
        self.label_48.setText(_translate("MainWindow", "????????"))
        self.descriptionvideo_timestamp_label_9.setText(_translate("MainWindow", "System Call Argument:"))
        self.descriptionvideo_timestamp_label_10.setText(_translate("MainWindow", "System Call Name:"))
        self.label_49.setText(_translate("MainWindow", "10-6-26 02:31:29"))
        self.label_50.setText(_translate("MainWindow", "??????"))
        self.descriptionvideo_timestamp_label_11.setText(_translate("MainWindow", "System Call Return Value:"))
        self.descriptionvideo_timestamp_label_13.setText(_translate("MainWindow", "System Call Type:"))
        self.label_52.setText(_translate("MainWindow", "??????"))
        self.label_53.setText(_translate("MainWindow", "?????"))
        self.description_tab.setTabText(self.description_tab.indexOf(self.descriptionsystemcall_tab), _translate("MainWindow", "System Call"))
        self.label_51.setText(_translate("MainWindow", "??????"))
        self.label_54.setText(_translate("MainWindow", "?????"))
        self.label_55.setText(_translate("MainWindow", "10-6-26 02:31:29"))
        self.descriptionvideo_timestamp_label_12.setText(_translate("MainWindow", "Process ID:"))
        self.label_56.setText(_translate("MainWindow", "????????"))
        self.descriptionvideo_timestamp_label_14.setText(_translate("MainWindow", "Parent Process Name:"))
        self.descriptionvideo_timestamp_label_15.setText(_translate("MainWindow", "Timestamp:"))
        self.label_57.setText(_translate("MainWindow", "??????"))
        self.descriptionvideo_timestamp_label_16.setText(_translate("MainWindow", "User Name:"))
        self.descriptionvideo_timestamp_label_17.setText(_translate("MainWindow", "Process Name:"))
        self.label_58.setText(_translate("MainWindow", "??????"))
        self.label_59.setText(_translate("MainWindow", "?????"))
        self.label_60.setText(_translate("MainWindow", "10-6-26 02:31:29"))
        self.descriptionvideo_timestamp_label_18.setText(_translate("MainWindow", "Status:"))
        self.label_61.setText(_translate("MainWindow", "????????"))
        self.descriptionvideo_timestamp_label_19.setText(_translate("MainWindow", "Memory Usage"))
        self.descriptionvideo_timestamp_label_20.setText(_translate("MainWindow", "Start Time:"))
        self.label_62.setText(_translate("MainWindow", "??????"))
        self.descriptionvideo_timestamp_label_21.setText(_translate("MainWindow", "Command:"))
        self.descriptionvideo_timestamp_label_22.setText(_translate("MainWindow", "Terminal:"))
        self.label_63.setText(_translate("MainWindow", "10-6-26 02:31:29"))
        self.label_64.setText(_translate("MainWindow", "??????"))
        self.descriptionvideo_timestamp_label_23.setText(_translate("MainWindow", "No. of Thread:"))
        self.descriptionvideo_timestamp_label_24.setText(_translate("MainWindow", "Process Priority:"))
        self.label_65.setText(_translate("MainWindow", "??????"))
        self.label_66.setText(_translate("MainWindow", "????????"))
        self.descriptionvideo_timestamp_label_25.setText(_translate("MainWindow", "Process Type:"))
        self.descriptionvideo_timestamp_label_26.setText(_translate("MainWindow", "CPU Percentage:"))
        self.label_67.setText(_translate("MainWindow", "?????"))
        self.descriptionvideo_timestamp_label_27.setText(_translate("MainWindow", "Process Privileges:"))
        self.description_tab.setTabText(self.description_tab.indexOf(self.descriptionprocess_tab), _translate("MainWindow", "Process"))
        self.label_68.setText(_translate("MainWindow", "10-6-26 02:31:29"))
        self.label_69.setText(_translate("MainWindow", "10-6-26 02:31:29"))
        self.label_70.setText(_translate("MainWindow", "????????"))
        self.descriptionvideo_timestamp_label_29.setText(_translate("MainWindow", "Application Name:"))
        self.descriptionvideo_timestamp_label_30.setText(_translate("MainWindow", "Visible:"))
        self.descriptionvideo_timestamp_label_31.setText(_translate("MainWindow", "Window Title:"))
        self.label_71.setText(_translate("MainWindow", "??????"))
        self.descriptionvideo_timestamp_label_32.setText(_translate("MainWindow", "Window Creation Time:"))
        self.descriptionvideo_timestamp_label_33.setText(_translate("MainWindow", "Maximized:"))
        self.label_72.setText(_translate("MainWindow", "????????"))
        self.descriptionvideo_timestamp_label_34.setText(_translate("MainWindow", "Primary Screen Resolution:"))
        self.label_74.setText(_translate("MainWindow", "??????"))
        self.descriptionvideo_timestamp_label_35.setText(_translate("MainWindow", "Window Destruction Time:"))
        self.descriptionvideo_timestamp_label_36.setText(_translate("MainWindow", "Minimized:"))
        self.label_75.setText(_translate("MainWindow", "????????"))
        self.label_76.setText(_translate("MainWindow", "??????"))
        self.label_77.setText(_translate("MainWindow", "??????"))
        self.label_78.setText(_translate("MainWindow", "10-6-26 02:31:29"))
        self.descriptionvideo_timestamp_label_38.setText(_translate("MainWindow", "Timestamp:"))
        self.descriptionvideo_timestamp_label_39.setText(_translate("MainWindow", "Window Style:"))
        self.descriptionvideo_timestamp_label_40.setText(_translate("MainWindow", "Window Position:"))
        self.label_81.setText(_translate("MainWindow", "??????"))
        self.descriptionvideo_timestamp_label_42.setText(_translate("MainWindow", "Window Placement Command:"))
        self.label_82.setText(_translate("MainWindow", "??????"))
        self.description_tab.setTabText(self.description_tab.indexOf(self.descriptionwindowhistory_tab), _translate("MainWindow", "Window History"))
        self.description_tab.setTabText(self.description_tab.indexOf(self.descriptionnetwork_tab), _translate("MainWindow", "Network Packet"))
        self.label_73.setText(_translate("MainWindow", "??????"))
        self.label_79.setText(_translate("MainWindow", "?????"))
        self.label_80.setText(_translate("MainWindow", "10-6-26 02:31:29"))
        self.descriptionvideo_timestamp_label_28.setText(_translate("MainWindow", "Mouse Action Value:"))
        self.label_83.setText(_translate("MainWindow", "????????"))
        self.descriptionvideo_timestamp_label_37.setText(_translate("MainWindow", "Active Window:"))
        self.descriptionvideo_timestamp_label_41.setText(_translate("MainWindow", "Timestamp:"))
        self.label_84.setText(_translate("MainWindow", "??????"))
        self.descriptionvideo_timestamp_label_43.setText(_translate("MainWindow", "Button:"))
        self.descriptionvideo_timestamp_label_44.setText(_translate("MainWindow", "Mouse Action:"))
        self.descriptionvideo_timestamp_label_45.setText(_translate("MainWindow", "Window Focus:"))
        self.label_85.setText(_translate("MainWindow", "??????"))
        self.description_tab.setTabText(self.description_tab.indexOf(self.descriptionmouse_tab), _translate("MainWindow", "Mouse Action"))
        self.descriptionvideo_timestamp_label_46.setText(_translate("MainWindow", "Keypress:"))
        self.descriptionvideo_timestamp_label_47.setText(_translate("MainWindow", "Timestamp:"))
        self.label_86.setText(_translate("MainWindow", "10-6-26 02:31:29"))
        self.label_87.setText(_translate("MainWindow", "??????"))
        self.description_tab.setTabText(self.description_tab.indexOf(self.descriptionkeystroke_tab), _translate("MainWindow", "Keystroke"))
        
        #DESCRIPTION DETAILED VIEW END



        item = self.tableWidget_24.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Video1"))
        item = self.tableWidget_24.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Timestamp"))
        item = self.tableWidget_24.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget_24.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MAC Address"))
        item = self.tableWidget_24.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        __sortingEnabled = self.tableWidget_24.isSortingEnabled()
        self.tableWidget_24.setSortingEnabled(False)
        item = self.tableWidget_24.item(0, 0)
        item.setText(_translate("MainWindow", "10-06-26 02:31:29,573"))
        item = self.tableWidget_24.item(0, 1)
        item.setText(_translate("MainWindow", "192.111.222.16"))
        item = self.tableWidget_24.item(0, 2)
        item.setText(_translate("MainWindow", "89:28:B2:C6:55:19"))
        item = self.tableWidget_24.item(0, 3)
        item.setText(_translate("MainWindow", "Lorem Ipsum"))
        self.tableWidget_24.setSortingEnabled(__sortingEnabled)
        self.pushButton_12.setText(_translate("MainWindow", "Add"))
        self.tabWidget_26.setTabText(self.tabWidget_26.indexOf(self.tab_102), _translate("MainWindow", "Annotation"))
        self.tabWidget_26.setTabText(self.tabWidget_26.indexOf(self.tab_103), _translate("MainWindow", "Tags"))
        self.toolBox_12.setItemText(self.toolBox_12.indexOf(self.detailed_view_accordion_14), _translate("MainWindow", "Detailed View of Selected Artifact"))
        self.toolBox_12.setItemText(self.toolBox_12.indexOf(self.visualization_accordion_14), _translate("MainWindow", "Visualization"))
        self.toolBox_12.setItemText(self.toolBox_12.indexOf(self.script_accordion_10), _translate("MainWindow", "Script"))
        self.toolBox_12.setItemText(self.toolBox_12.indexOf(self.history_accordion_10), _translate("MainWindow", "History"))
        self.toolBox_12.setItemText(self.toolBox_12.indexOf(self.log_accordion_10), _translate("MainWindow", "Log Content"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Sync"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Detailed View"))
        self.menuAVERT.setTitle(_translate("MainWindow", "AVERT"))


    def add_sections(self):
        """adds a collapsible sections for every 
        (title, widget) tuple in self.sections
        """
        for (title, widget) in self.sections:
            button1 = self.add_button(title)
            section1 = self.add_widget(button1, widget)
            button1.addChild(section1)

    def define_sections(self):
        """reimplement this to define all your sections
        and add them as (title, widget) tuples to self.sections
        """
        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        layout.addWidget(QtWidgets.QCalendarWidget())
        title = "Selected Artifacts"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        self.checkBox_Visualization = QtWidgets.QCheckBox()
        self.checkBox_Visualization.setObjectName("checkBox_Visualization")
        layout.addWidget(self.checkBox_Visualization)
        
        title = "Visualization"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        layout = QVBoxLayout(widget)
        
        
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox = QtWidgets.QCheckBox()
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(QtWidgets.QCheckBox())
        self.verticalLayout_6.addWidget(QtWidgets.QCheckBox())
        self.verticalLayout_6.addWidget(QtWidgets.QCheckBox())
        self.verticalLayout_6.addWidget(self.checkBox)
        layout.addLayout(self.verticalLayout_6)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_31 = QtWidgets.QLabel()
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 6, 1, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit()
        self.textEdit_3.setMaximumSize(QtCore.QSize(400, 25))
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_4.addWidget(self.textEdit_3, 2, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton()
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 6, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel()
        self.label_32.setStyleSheet("")
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel()
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_33 = QtWidgets.QLabel()
        self.verticalLayout_6.addLayout(self.gridLayout_4)

        title = "Script"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        layout.addWidget(QtWidgets.QCheckBox())
        title = "History"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        layout.addWidget(QtWidgets.QCheckBox())
        title = "Log Content"
        self.sections.append((title, widget))
        # self.gridLayout_2.addWidget(widget, 7, 2, 1, 1)

    def add_button(self, title):
        """creates a QTreeWidgetItem containing a button 
        to expand or collapse its section
        """
        item = QTreeWidgetItem()
        self.tree.addTopLevelItem(item)
        self.tree.setItemWidget(item, 0, SectionExpandButton(item, text = title))
        return item

    def add_widget(self, button, widget):
        """creates a QWidgetItem containing the widget,
        as child of the button-QWidgetItem
        """
        section = QTreeWidgetItem(button)
        section.setDisabled(True)
        self.tree.setItemWidget(section, 0, widget)
        return section

class SectionExpandButton(QPushButton):
    """a QPushbutton that can expand or collapse its section
    """
    def __init__(self, item, text = "", parent = None):
        super().__init__(text, parent)
        self.section = item
        self.clicked.connect(self.on_clicked)

    def on_clicked(self):
        """toggle expand/collapse of section by clicking
        """
        if self.section.isExpanded():
            self.section.setExpanded(False)
        else:
            self.section.setExpanded(True)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    app.exec()
    