import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QPushButton, QDialog, QTreeWidget, QTreeWidgetItem, QVBoxLayout,
                             QHBoxLayout, QFrame, QLabel, QApplication, QMainWindow)
# from PyQt6 import QtCore, QtGui, QtWidgets
# from PyQt6.QtWidgets import (QPushButton, QDialog, QTreeWidget, QTreeWidgetItem, QVBoxLayout,
                            #  QHBoxLayout, QFrame, QLabel,
                            #  QApplication, QApplication, QMainWindow, QPushButton)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.tree = QTreeWidget()
        self.tree.setHeaderHidden(True)
        self.sections = []
        self.define_sections()
        self.add_sections()
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1792, 1120)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1771, 1051))
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        # self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.tab_1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 1, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_1)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        # self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMaximumSize(QtCore.QSize(400, 25))
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_2.addWidget(self.textEdit_2, 2, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.tab_1)
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_1)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        self.label_8.setMaximumSize(QtCore.QSize(20, 20))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_2.setMaximumSize(QtCore.QSize(150, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_20 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_3.addWidget(self.checkBox_20, 15, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_1)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_1)
        self.label_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_4.setMaximumSize(QtCore.QSize(150, 20))
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_3.addWidget(self.comboBox_4, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_1)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 9, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_1)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_1)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 4, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_1)
        self.label_30.setStyleSheet("")
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 16, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 17, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_3.setMaximumSize(QtCore.QSize(150, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_1)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 1, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_3.addWidget(self.checkBox_18, 10, 1, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_3.addWidget(self.checkBox_17, 9, 1, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_3.addWidget(self.checkBox_14, 5, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_1)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 13, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_1)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 14, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_1)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 10, 0, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_3.addWidget(self.checkBox_21, 8, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_1)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_1)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_3.addWidget(self.checkBox_15, 6, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.tab_1)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_3.addWidget(self.dateEdit, 17, 1, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_22.setText("")
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_3.addWidget(self.checkBox_22, 12, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_1)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 6, 0, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_24.setText("")
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_3.addWidget(self.checkBox_24, 14, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 19, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_1)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 15, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_3.addWidget(self.checkBox_16, 7, 1, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_23.setText("")
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_3.addWidget(self.checkBox_23, 13, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_1)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 11, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_1)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 12, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 18, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_1)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 8, 0, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab_1)
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_3.addWidget(self.checkBox_19, 11, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_1)
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.tab_1)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_3.addWidget(self.timeEdit, 18, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_1)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_29.setStyleSheet("")
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 16, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 20, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_1)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_3.addWidget(self.dateEdit_2, 19, 1, 1, 1)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.tab_1)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout_3.addWidget(self.timeEdit_2, 20, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 7, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.tab_1)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 7, 1, 1, 1)
        # self.pushButton_2 = QtWidgets.QPushButton(self.tab_1)
        # self.pushButton_2.setMaximumSize(QtCore.QSize(150, 16777215))
        # self.pushButton_2.setObjectName("pushButton_2")
        # # self.gridLayout_2.addWidget(self.pushButton_2, 7, 2, 1, 1)
        # widget = QFrame(self.tree)
        # layout = QHBoxLayout(widget)
        # # layout.addWidget(QtWidgets.QCheckBox())
        # title = "Log Content"
        # # self.sections.append((title, widget))
        # button1 = self.add_button(title)
        # section1 = self.add_widget(button1, widget)
        # button1.addChild(section1)
        # layout.addWidget(button1)
        
        # self.gridLayout_2.addLayout(layout, 7, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(self.checkBox)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar.setGeometry(QtCore.QRect(220, 80, 291, 121))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1792, 22))
        self.menubar.setObjectName("menubar")
        self.menuAVERT = QtWidgets.QMenu(self.menubar)
        self.menuAVERT.setObjectName("menuAVERT")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAVERT.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.tree.setHeaderHidden(True)
        # layout = QVBoxLayout(self.tab_1)
        self.verticalLayout_5.addWidget(self.tree)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "AVERT RESULT"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "Expression"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.label_10.setText(_translate("MainWindow", "Search"))
        self.label_6.setText(_translate("MainWindow", "Search Expression"))
        self.label_8.setText(_translate("MainWindow", "Tag"))
        self.label_16.setText(_translate("MainWindow", "Type"))
        self.label_15.setText(_translate("MainWindow", "MAC Address"))
        self.label_22.setText(_translate("MainWindow", "Process"))
        self.label_20.setText(_translate("MainWindow", "Video"))
        self.label_17.setText(_translate("MainWindow", "Value"))
        self.label_30.setText(_translate("MainWindow", "Value"))
        self.label.setText(_translate("MainWindow", "Start Date"))
        self.label_14.setText(_translate("MainWindow", "Value"))
        self.label_26.setText(_translate("MainWindow", "System Call"))
        self.label_11.setText(_translate("MainWindow", "User Profile"))
        self.label_27.setText(_translate("MainWindow", "History"))
        self.label_23.setText(_translate("MainWindow", "Keystroke"))
        self.label_18.setText(_translate("MainWindow", "All Arifact Types"))
        self.label_13.setText(_translate("MainWindow", "Filters"))
        self.label_19.setText(_translate("MainWindow", "Still Screenshot"))
        self.label_3.setText(_translate("MainWindow", "End Date"))
        self.label_28.setText(_translate("MainWindow", "Log"))
        self.label_24.setText(_translate("MainWindow", "Mouse Action"))
        self.label_25.setText(_translate("MainWindow", "Window History"))
        self.label_2.setText(_translate("MainWindow", "Start Time"))
        self.label_21.setText(_translate("MainWindow", "Network Packet"))
        self.label_12.setText(_translate("MainWindow", "IP Address"))
        self.label_29.setText(_translate("MainWindow", "Date and Time"))
        self.label_4.setText(_translate("MainWindow", "End Time"))
        self.pushButton_2.setText(_translate("MainWindow", "Search"))
        self.pushButton_3.setText(_translate("MainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Home"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Sync"))
        self.menuAVERT.setTitle(_translate("MainWindow", "AVERT"))


    def add_sections(self):
        """adds a collapsible sections for every 
        (title, widget) tuple in self.sections
        """
        for (title, widget) in self.sections:
            button1 = self.add_button(title)
            section1 = self.add_widget(button1, widget)
            button1.addChild(section1)

    def define_sections(self):
        """reimplement this to define all your sections
        and add them as (title, widget) tuples to self.sections
        """
        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        layout.addWidget(QtWidgets.QCalendarWidget())
        title = "Selected Artifacts"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        self.checkBox_Visualization = QtWidgets.QCheckBox()
        self.checkBox_Visualization.setObjectName("checkBox_Visualization")
        layout.addWidget(self.checkBox_Visualization)
        
        title = "Visualization"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        # self.tab_2 = QtWidgets.QWidget(widget)
        # self.tab_2.setObjectName("tab_2")
        layout = QVBoxLayout(widget)
        
        
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox = QtWidgets.QCheckBox()
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(QtWidgets.QCheckBox())
        self.verticalLayout_6.addWidget(QtWidgets.QCheckBox())
        self.verticalLayout_6.addWidget(QtWidgets.QCheckBox())
        self.verticalLayout_6.addWidget(self.checkBox)
        layout.addLayout(self.verticalLayout_6)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_31 = QtWidgets.QLabel()
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 6, 1, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit()
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.textEdit_3.sizePolicy().hasHeightForWidth())
        # self.textEdit_3.setSizePolicy(sizePolicy)
        self.textEdit_3.setMaximumSize(QtCore.QSize(400, 25))
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_4.addWidget(self.textEdit_3, 2, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton()
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 6, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel()
        self.label_32.setStyleSheet("")
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel()
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_33 = QtWidgets.QLabel()
        self.verticalLayout_6.addLayout(self.gridLayout_4)

        title = "Script"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        layout.addWidget(QtWidgets.QCheckBox())
        title = "History"
        self.sections.append((title, widget))

        widget = QFrame(self.tree)
        layout = QHBoxLayout(widget)
        layout.addWidget(QtWidgets.QCheckBox())
        title = "Log Content"
        self.sections.append((title, widget))
        # self.gridLayout_2.addWidget(widget, 7, 2, 1, 1)

    def add_button(self, title):
        """creates a QTreeWidgetItem containing a button 
        to expand or collapse its section
        """
        item = QTreeWidgetItem()
        self.tree.addTopLevelItem(item)
        self.tree.setItemWidget(item, 0, SectionExpandButton(item, text = title))
        return item

    def add_widget(self, button, widget):
        """creates a QWidgetItem containing the widget,
        as child of the button-QWidgetItem
        """
        section = QTreeWidgetItem(button)
        section.setDisabled(True)
        self.tree.setItemWidget(section, 0, widget)
        return section

class SectionExpandButton(QPushButton):
    """a QPushbutton that can expand or collapse its section
    """
    def __init__(self, item, text = "", parent = None):
        super().__init__(text, parent)
        self.section = item
        self.clicked.connect(self.on_clicked)

    def on_clicked(self):
        """toggle expand/collapse of section by clicking
        """
        if self.section.isExpanded():
            self.section.setExpanded(False)
        else:
            self.section.setExpanded(True)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    app.exec()
    