# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AvertUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import datetime

i = '11/28/2021 01:00:00 - 11/29/2021 01:00:00'
i = i.split('-')
t = i[0].split(' ')
print(t)
date = []
value = ''
t.remove('')

for j in t:
    for i in j:
        if i.isnumeric():
            value = value + i
        else:
            date.append(int(value))
            value = ''
    date.append(int(value))
    value = ''
#date.append(int(value))

print(date)

'''
x = datetime.datetime(2021, 5, 17, 1, 15, 10)
print(x)
y = datetime.datetime.now()
#x = x.strftime('%x ') + x.strftime('%X')
add = datetime.timedelta(seconds=1)
x += add
print(x)
print(y)
print(x <= y)
'''
