from PyQt5 import QtCore, QtGui, QtWidgets
from view.components import addition_for_synctab
from view.sync_tab.progress_bar import ProgressBar

class Sync:
	def __init__(self):
		self.tab_3 = QtWidgets.QWidget()
		self.tab_3.setObjectName("tab_3")
		self.gridLayout_38 = QtWidgets.QGridLayout(self.tab_3)
		self.gridLayout_38.setObjectName("gridLayout_38")
		self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_3)
		self.scrollArea_3.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.scrollArea_3.setFrameShadow(QtWidgets.QFrame.Plain)
		self.scrollArea_3.setWidgetResizable(True)
		self.scrollArea_3.setObjectName("scrollArea_3")
		self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
		self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1331, 944))
		self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
		self.gridLayout_51 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
		self.gridLayout_51.setObjectName("gridLayout_51")
		self.syncbasicinformation_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
		self.syncbasicinformation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.syncbasicinformation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
		self.syncbasicinformation_frame.setObjectName("syncbasicinformation_frame")
		self.formLayout_12 = QtWidgets.QFormLayout(self.syncbasicinformation_frame)
		self.formLayout_12.setObjectName("formLayout_12")
		self.fromIPlabel_label = QtWidgets.QLabel(self.syncbasicinformation_frame)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.fromIPlabel_label.sizePolicy().hasHeightForWidth())
		self.fromIPlabel_label.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(16)
		self.fromIPlabel_label.setFont(font)
		self.fromIPlabel_label.setObjectName("fromIPlabel_label")
		self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fromIPlabel_label)
		self.fromMAClabel_label = QtWidgets.QLabel(self.syncbasicinformation_frame)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.fromMAClabel_label.sizePolicy().hasHeightForWidth())
		self.fromMAClabel_label.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(16)
		self.fromMAClabel_label.setFont(font)
		self.fromMAClabel_label.setObjectName("fromMAClabel_label")
		self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fromMAClabel_label)
		self.fromMACval_label = QtWidgets.QLabel(self.syncbasicinformation_frame)
		font = QtGui.QFont()
		font.setPointSize(16)
		self.fromMACval_label.setFont(font)
		self.fromMACval_label.setObjectName("fromMACval_label")
		self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fromMACval_label)
		self.toIPlabel_label = QtWidgets.QLabel(self.syncbasicinformation_frame)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.toIPlabel_label.sizePolicy().hasHeightForWidth())
		self.toIPlabel_label.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(16)
		self.toIPlabel_label.setFont(font)
		self.toIPlabel_label.setObjectName("toIPlabel_label")
		self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.toIPlabel_label)
		self.toIPval_lineEdit = QtWidgets.QLineEdit(self.syncbasicinformation_frame)
		font = QtGui.QFont()
		font.setPointSize(16)
		self.toIPval_lineEdit.setFont(font)
		self.toIPval_lineEdit.setText("")
		self.toIPval_lineEdit.setObjectName("toIPval_lineEdit")
		self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.toIPval_lineEdit)
		self.fromIPval_label = QtWidgets.QLabel(self.syncbasicinformation_frame)
		font = QtGui.QFont()
		font.setPointSize(16)
		self.fromIPval_label.setFont(font)
		self.fromIPval_label.setObjectName("fromIPval_label")
		self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fromIPval_label)
		self.gridLayout_51.addWidget(self.syncbasicinformation_frame, 0, 0, 1, 1)
		self.sync_piechart_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
		self.sync_piechart_frame.setMinimumSize(QtCore.QSize(400, 200))
		self.sync_piechart_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.sync_piechart_frame.setFrameShadow(QtWidgets.QFrame.Raised)
		self.sync_piechart_frame.setObjectName("sync_piechart_frame")
		self.gridLayout_52 = QtWidgets.QGridLayout(self.sync_piechart_frame)
		self.gridLayout_52.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_52.setObjectName("gridLayout_52")
		self.label_26 = QtWidgets.QLabel(self.sync_piechart_frame)
		self.label_26.setObjectName("label_26")
		# add sync graph
		self.gridLayout_52.addWidget(addition_for_synctab.piechart_for_synctab(), 0, 0, 1, 1)
		self.gridLayout_51.addWidget(self.sync_piechart_frame, 0, 1, 1, 1)
		self.frame_15 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
		self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_15.setObjectName("frame_15")
		self.gridLayout_39 = QtWidgets.QGridLayout(self.frame_15)
		self.gridLayout_39.setObjectName("gridLayout_39")
		self.allexcludingvideo_btn = QtWidgets.QPushButton(self.frame_15)
		font = QtGui.QFont()
		font.setPointSize(16)
		self.allexcludingvideo_btn.setFont(font)
		self.allexcludingvideo_btn.setObjectName("allexcludingvideo_btn")
		self.gridLayout_39.addWidget(self.allexcludingvideo_btn, 0, 0, 1, 1)
		self.allincludingvideo_btn = QtWidgets.QPushButton(self.frame_15)
		font = QtGui.QFont()
		font.setPointSize(16)
		self.allincludingvideo_btn.setFont(font)
		self.allincludingvideo_btn.setObjectName("allincludingvideo_btn")
		self.gridLayout_39.addWidget(self.allincludingvideo_btn, 0, 1, 1, 1)
		self.errormessage = QtWidgets.QLabel(self.frame_15)
		self.errormessage.setStyleSheet("color: red")
		self.errormessage.setObjectName("errormessage")
		# make it not visible at first
		self.errormessage.setVisible(False)
		self.gridLayout_39.addWidget(self.errormessage, 1, 0, 1, 2)
		self.sync_btn = QtWidgets.QPushButton(self.frame_15)
		font = QtGui.QFont()
		font.setPointSize(16)
		self.sync_btn.setFont(font)
		self.sync_btn.setObjectName("sync_btn")
		self.gridLayout_39.addWidget(self.sync_btn, 2, 0, 1, 1)
		self.cancelall_btn = QtWidgets.QPushButton(self.frame_15)
		font = QtGui.QFont()
		font.setPointSize(16)
		self.cancelall_btn.setFont(font)
		self.cancelall_btn.setObjectName("cancelall_btn")
		self.gridLayout_39.addWidget(self.cancelall_btn, 2, 1, 1, 1)
		self.gridLayout_51.addWidget(self.frame_15, 0, 2, 1, 1)
		self.progresssection = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
		# sync connector
		addition_for_synctab.btns_connector_in_synctab(
				self.allexcludingvideo_btn, self.allincludingvideo_btn, self.sync_btn, self.errormessage)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.progresssection.sizePolicy().hasHeightForWidth())
		self.progresssection.setSizePolicy(sizePolicy)
		self.progresssection.setObjectName("progresssection")
		self.gridLayout_40 = QtWidgets.QGridLayout(self.progresssection)
		self.gridLayout_40.setObjectName("gridLayout_40")

		self.stillscreenshot_frame = ProgressBar(self.progresssection, "Still Screenshot")
		self.gridLayout_40.addWidget(self.stillscreenshot_frame.getPBarFrame(), 0, 0, 1, 1)

		self.keystroke_frame = ProgressBar(self.progresssection, "Keystroke")
		self.gridLayout_40.addWidget(self.keystroke_frame.getPBarFrame(), 2,0,1,1)
		
		self.history_frame = ProgressBar(self.progresssection, "History")
		self.gridLayout_40.addWidget(self.history_frame.getPBarFrame(), 4,0,1,1)

		self.video_frame = ProgressBar(self.progresssection, "Video")
		self.gridLayout_40.addWidget(self.video_frame.getPBarFrame(), 0,1,1,1)

		self.log_frame = ProgressBar(self.progresssection, "Log")
		self.gridLayout_40.addWidget(self.log_frame.getPBarFrame(), 4,1,1,1)
		
		self.mouseaction_frame = ProgressBar(self.progresssection, "Mouse Section")
		self.gridLayout_40.addWidget(self.mouseaction_frame.getPBarFrame(), 2,1,1,1)

		self.windowhistory_frame = ProgressBar(self.progresssection, "Window History")
		self.gridLayout_40.addWidget(self.windowhistory_frame.getPBarFrame(), 3,0,1,1)

		self.networkactivitydata_frame = ProgressBar(self.progresssection, "Network Activity")
		self.gridLayout_40.addWidget(self.networkactivitydata_frame.getPBarFrame(), 1,1,1,1)

		self.systemcall_frame = ProgressBar(self.progresssection, "System Call")
		self.gridLayout_40.addWidget(self.systemcall_frame.getPBarFrame(), 3,1,1,1)

		self.process_frame = ProgressBar(self.progresssection, "Process")
		self.gridLayout_40.addWidget(self.process_frame.getPBarFrame(), 1,0,1,1)

		self.gridLayout_51.addWidget(self.progresssection, 1, 0, 1, 3)
		self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
		self.gridLayout_38.addWidget(self.scrollArea_3, 0, 0, 1, 1)
		_translate = QtCore.QCoreApplication.translate
		self.fromIPlabel_label.setText(_translate("MainWindow", "From Analyst\'s IP Address:"))
		self.fromMAClabel_label.setText(_translate("MainWindow", "From Analyst\'s MAC Address:"))
		self.fromMACval_label.setText(_translate("MainWindow", "3D-9F-1A-82-2C-0E"))
		self.toIPlabel_label.setText(_translate("MainWindow", "To Analyst\'s IP Address:"))
		self.toIPval_lineEdit.setPlaceholderText(_translate("MainWindow", "Enter IP Address"))
		self.fromIPval_label.setText(_translate("MainWindow", "127.0.0.1"))
		self.label_26.setText(_translate("MainWindow", "Sync Section"))
		self.allexcludingvideo_btn.setText(_translate("MainWindow", "All Excluding Video"))
		self.allincludingvideo_btn.setText(_translate("MainWindow", "All Including Video"))
		self.errormessage.setText(_translate("MainWindow", "Error: Please select video sync scope above."))
		self.sync_btn.setText(_translate("MainWindow", "Sync"))
		self.cancelall_btn.setText(_translate("MainWindow", "Cancel All Sync"))
		self.progresssection.setTitle(_translate("MainWindow", "Prgress Section"))

	def get_tab(self):
		return self.tab_3