# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AvertUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from view.components import addition_for_synctab, bar_graph, pics_for_detailedview
from view.components import result_table
from view.home_tab.home import Home
from view.configuration_tab.configuration import Configuration
from view.sync_tab.sync import Sync

table_result = None
clicks = []
selected = None
attain = []


class Ui_MainWindow():
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1272, 835)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")

        """tab_1 start"""
        hometab = Home()
        self.tab_1 = hometab.get_tab()
        self.tabWidget.addTab(self.tab_1, "HOME")
        """tab_1 end"""


        """tab_2 start"""
        configurationtab = Configuration()
        self.tab_2 = configurationtab.get_tab()
        self.tabWidget.addTab(self.tab_2, "Configuration")
        """tab_2 end"""


        """tab_3 start"""
        synctab = Sync()
        self.tab_3 = synctab.get_tab()
        self.tabWidget.addTab(self.tab_3, "Sync")
        """tab_3 end"""

        self.gridLayout_20.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1272, 24))
        self.menubar.setObjectName("menubar")
        self.menuAVERT = QtWidgets.QMenu(self.menubar)
        self.menuAVERT.setObjectName("menuAVERT")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuAVERT.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        # self.DetailedViewTab.setCurrentIndex(0)
        # self.description_tab.setCurrentIndex(0)
        # self.toolBox.setCurrentIndex(0)
        # self.visualization_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.menuAVERT.setTitle(_translate("MainWindow", "AVERT"))

        # table_result.avert_result_table.cellClicked.connect(self.exportRow)

    def updateTable(self, attain):
        global table_result
        table_result.printwhatv()
        table_result.populateTable(attain)
        # self.verticalLayout_3.addWidget(table_result.getTable()) si jala
        # print(attain)

    def getResultTable(self):
        global table_result
        return table_result

    def exportRow(self, index):
        if index not in clicks:
            clicks.append(index)
            selected = index
            self.changeDetailView(selected)
            print(selected)
        else:
            clicks.remove(index)
            selected = None

    def updateTable(self, attain1):
        global attain
        global table_result
        attain = attain1
        table_result.printwhatv()
        table_result.populateTable(attain)
        # self.verticalLayout_3.addWidget(table_result.getTable()) si jala
        # print(attain)
    
    def changeDetailView(self, selected):
        _translate = QtCore.QCoreApplication.translate
        global attain
        curdata = attain[selected]
        item = self.tableWidget_38.item(0, 0)
        item.setText(_translate("MainWindow", curdata['ip_address']))
        item = self.tableWidget_38.item(0, 1)
        item.setText(_translate("MainWindow", curdata['mac_address']))
